ESP-IDF Firmware: cdc.c File Reference
cdc.c File Reference
#include <stdint.h>
#include "esp_check.h"
#include "esp_err.h"
#include "esp_log.h"
#include "tusb.h"
#include "cdc.h"
Macros
#define CDC_INTF_NUM CFG_TUD_CDC
Functions
esp_tusb_cdc_t * tinyusb_cdc_get_intf (int itf_num)
Return interface of a CDC device.
static esp_err_t cdc_obj_check (int itf, bool expected_inited, tusb_class_code_t expected_type)
static esp_err_t tusb_cdc_comm_init (int itf)
static esp_err_t tusb_cdc_deinit_comm (int itf)
static esp_err_t tusb_cdc_data_init (int itf)
static esp_err_t tusb_cdc_deinit_data (int itf)
esp_err_t tinyusb_cdc_init (int itf, const tinyusb_config_cdc_t *cfg)
Initializing CDC basic object.
esp_err_t tinyusb_cdc_deinit (int itf)
De-initializing CDC. Clean its objects.
Variables
static esp_tusb_cdc_t * cdc_obj [CFG_TUD_CDC] = {}
static const char * TAG = "tusb_cdc"
Macro Definition Documentation
CDC_INTF_NUM
#define CDC_INTF_NUM CFG_TUD_CDC
Definition at line 14 of file cdc.c.
Referenced by tinyusb_cdc_get_intf().
Function Documentation
cdc_obj_check()
esp_err_t cdc_obj_check (int itf, bool expected_inited, tusb_class_code_t expected_type) static
Definition at line 26 of file cdc.c.
{
    esp_tusb_cdc_t *this_itf = tinyusb_cdc_get_intf(itf);
    bool inited = (this_itf != NULL);
    ESP_RETURN_ON_FALSE(expected_inited == inited, ESP_ERR_INVALID_STATE, TAG, "Wrong state of the interface. Expected state: %s", expected_inited ? "initialized" : "not initialized");
    ESP_RETURN_ON_FALSE(!(inited && (expected_type != -1) && !(this_itf->type == expected_type)), ESP_ERR_INVALID_STATE, TAG, "Wrong type of the interface. Should be : 0x%x (tusb_class_code_t)", expected_type);
    return ESP_OK;
}
References ESP_OK, TAG, tinyusb_cdc_get_intf(), and esp_tusb_cdc_t::type.
Referenced by tinyusb_cdc_deinit(), tinyusb_cdc_init(), tusb_cdc_comm_init(), tusb_cdc_data_init(), tusb_cdc_deinit_comm(), and tusb_cdc_deinit_data().
tinyusb_cdc_deinit()
esp_err_t tinyusb_cdc_deinit (int itf)
De-initializing CDC. Clean its objects.
Parameters
itf - number of a CDC object
Returns
esp_err_t ESP_OK, ESP_ERR_INVALID_ARG, ESP_ERR_INVALID_STATE
Definition at line 96 of file cdc.c.
{
    ESP_RETURN_ON_ERROR(cdc_obj_check(itf, true, -1), TAG, "cdc_obj_check failed");
    ESP_LOGD(TAG, "Deinit CDC %d", itf);
    if (cdc_obj[itf]->type == TUSB_CLASS_CDC) {
        ESP_RETURN_ON_ERROR(tusb_cdc_deinit_comm(itf), TAG, "tusb_cdc_deinit_comm failed");
    } else if (cdc_obj[itf]->type == TUSB_CLASS_CDC_DATA) {
        ESP_RETURN_ON_ERROR(tusb_cdc_deinit_data(itf), TAG, "tusb_cdc_deinit_data failed");
    } else {
        return ESP_ERR_INVALID_ARG;
    }
    return ESP_OK;
}
References cdc_obj, cdc_obj_check(), ESP_LOGD, ESP_OK, ESP_RETURN_ON_ERROR, TAG, tusb_cdc_deinit_comm(), and tusb_cdc_deinit_data().
Referenced by tusb_cdc_acm_init().
tinyusb_cdc_get_intf()
esp_tusb_cdc_t * tinyusb_cdc_get_intf (int itf_num)
Return interface of a CDC device.
Parameters
itf_num
Returns
esp_tusb_cdc_t* pointer to the interface or (NULL) on error
Definition at line 18 of file cdc.c.
{
    if (itf_num >= CDC_INTF_NUM || itf_num < 0) {
        return NULL;
    }
    return cdc_obj[itf_num];
}
References CDC_INTF_NUM, and cdc_obj.
Referenced by alloc_obj(), cdc_obj_check(), free_obj(), and get_acm().
tinyusb_cdc_init()
esp_err_t tinyusb_cdc_init (int itf, const tinyusb_config_cdc_t * cfg)
Initializing CDC basic object.
Parameters
itf - number of a CDC object
cfg - CDC configuration structure
Returns
esp_err_t ESP_OK or ESP_FAIL
Definition at line 80 of file cdc.c.
{
    ESP_RETURN_ON_ERROR(cdc_obj_check(itf, false, -1), TAG, "cdc_obj_check failed");
    ESP_LOGD(TAG, "Init CDC %d", itf);
    if (cfg->cdc_class == TUSB_CLASS_CDC) {
        ESP_RETURN_ON_ERROR(tusb_cdc_comm_init(itf), TAG, "tusb_cdc_comm_init failed");
        cdc_obj[itf]->cdc_subclass.comm_subclass = cfg->cdc_subclass.comm_subclass;
    } else {
        ESP_RETURN_ON_ERROR(tusb_cdc_data_init(itf), TAG, "tusb_cdc_data_init failed");
        cdc_obj[itf]->cdc_subclass.data_subclass = cfg->cdc_subclass.data_subclass;
    }
    cdc_obj[itf]->usb_dev = cfg->usb_dev;
    return ESP_OK;
}
References tinyusb_config_cdc_t::cdc_class, cdc_obj, cdc_obj_check(), tinyusb_config_cdc_t::cdc_subclass, tinyusb_config_cdc_t::comm_subclass, tinyusb_config_cdc_t::data_subclass, ESP_LOGD, ESP_OK, ESP_RETURN_ON_ERROR, TAG, tusb_cdc_comm_init(), tusb_cdc_data_init(), and tinyusb_config_cdc_t::usb_dev.
Referenced by tusb_cdc_acm_init().
tusb_cdc_comm_init()
esp_err_t tusb_cdc_comm_init (int itf) static
Definition at line 36 of file cdc.c.
{
    ESP_RETURN_ON_ERROR(cdc_obj_check(itf, false, -1), TAG, "cdc_obj_check failed");
    cdc_obj[itf] = calloc(1, sizeof(esp_tusb_cdc_t));
    if (cdc_obj[itf] != NULL) {
        cdc_obj[itf]->type = TUSB_CLASS_CDC;
        ESP_LOGD(TAG, "CDC Comm class initialized");
        return ESP_OK;
    } else {
        ESP_LOGE(TAG, "CDC Comm initialization error");
        return ESP_FAIL;
    }
}
References cdc_obj, cdc_obj_check(), ESP_LOGD, ESP_OK, ESP_RETURN_ON_ERROR, and TAG.
Referenced by tinyusb_cdc_init().
tusb_cdc_data_init()
esp_err_t tusb_cdc_data_init (int itf) static
Definition at line 58 of file cdc.c.
{
    ESP_RETURN_ON_ERROR(cdc_obj_check(itf, false, TUSB_CLASS_CDC_DATA), TAG, "cdc_obj_check failed");
    cdc_obj[itf] = calloc(1, sizeof(esp_tusb_cdc_t));
    if (cdc_obj[itf] != NULL) {
        cdc_obj[itf]->type = TUSB_CLASS_CDC_DATA;
        ESP_LOGD(TAG, "CDC Data class initialized");
        return ESP_OK;
    } else {
        ESP_LOGE(TAG, "CDC Data initialization error");
        return ESP_FAIL;
    }
}
References cdc_obj, cdc_obj_check(), ESP_LOGD, ESP_OK, ESP_RETURN_ON_ERROR, and TAG.
Referenced by tinyusb_cdc_init().
tusb_cdc_deinit_comm()
esp_err_t tusb_cdc_deinit_comm (int itf) static
Definition at line 50 of file cdc.c.
{
    ESP_RETURN_ON_ERROR(cdc_obj_check(itf, true, TUSB_CLASS_CDC), TAG, "cdc_obj_check failed");
    free(cdc_obj[itf]);
    cdc_obj[itf] = NULL;
    return ESP_OK;
}
References cdc_obj, cdc_obj_check(), ESP_OK, ESP_RETURN_ON_ERROR, and TAG.
Referenced by tinyusb_cdc_deinit().
tusb_cdc_deinit_data()
esp_err_t tusb_cdc_deinit_data (int itf) static
Definition at line 72 of file cdc.c.
{
    ESP_RETURN_ON_ERROR(cdc_obj_check(itf, true, TUSB_CLASS_CDC_DATA), TAG, "cdc_obj_check failed");
    free(cdc_obj[itf]);
    cdc_obj[itf] = NULL;
    return ESP_OK;
}
References cdc_obj, cdc_obj_check(), ESP_OK, ESP_RETURN_ON_ERROR, and TAG.
Referenced by tinyusb_cdc_deinit().
Variable Documentation
cdc_obj
esp_tusb_cdc_t* cdc_obj[CFG_TUD_CDC] = {} static
Definition at line 15 of file cdc.c.
{};
Referenced by tinyusb_cdc_deinit(), tinyusb_cdc_get_intf(), tinyusb_cdc_init(), tusb_cdc_comm_init(), tusb_cdc_data_init(), tusb_cdc_deinit_comm(), and tusb_cdc_deinit_data().
TAG
const char* TAG = "tusb_cdc" static
Definition at line 16 of file cdc.c.