ESP-IDF Firmware: cdc.h File Reference
cdc.h File Reference
#include <stdint.h>
#include "freertos/FreeRTOS.h"
#include "freertos/semphr.h"
#include "freertos/timers.h"
#include "tusb.h"
#include "tinyusb_types.h"
Data Structures
struct tinyusb_config_cdc_t
struct esp_tusb_cdc_t
Enumerations
enum cdc_data_sublcass_type_t { TINYUSB_CDC_DATA = 0x00 }
Functions
esp_err_t tinyusb_cdc_init (int itf, const tinyusb_config_cdc_t *cfg)
Initializing CDC basic object.
esp_err_t tinyusb_cdc_deinit (int itf)
De-initializing CDC. Clean its objects.
esp_tusb_cdc_t * tinyusb_cdc_get_intf (int itf_num)
Return interface of a CDC device.
Enumeration Type Documentation
cdc_data_sublcass_type_t
enum cdc_data_sublcass_type_t
Enumerator
TINYUSB_CDC_DATA
Definition at line 22 of file cdc.h.
             {
    TINYUSB_CDC_DATA =          0x00,
} cdc_data_sublcass_type_t; // CDC120 specification
Function Documentation
tinyusb_cdc_deinit()
esp_err_t tinyusb_cdc_deinit (int itf)
De-initializing CDC. Clean its objects.
Parameters
itf - number of a CDC object
Returns
esp_err_t ESP_OK, ESP_ERR_INVALID_ARG, ESP_ERR_INVALID_STATE
Definition at line 96 of file cdc.c.
{
    ESP_RETURN_ON_ERROR(cdc_obj_check(itf, true, -1), TAG, "cdc_obj_check failed");
    ESP_LOGD(TAG, "Deinit CDC %d", itf);
    if (cdc_obj[itf]->type == TUSB_CLASS_CDC) {
        ESP_RETURN_ON_ERROR(tusb_cdc_deinit_comm(itf), TAG, "tusb_cdc_deinit_comm failed");
    } else if (cdc_obj[itf]->type == TUSB_CLASS_CDC_DATA) {
        ESP_RETURN_ON_ERROR(tusb_cdc_deinit_data(itf), TAG, "tusb_cdc_deinit_data failed");
    } else {
        return ESP_ERR_INVALID_ARG;
    }
    return ESP_OK;
}
References cdc_obj, cdc_obj_check(), ESP_LOGD, ESP_OK, ESP_RETURN_ON_ERROR, TAG, tusb_cdc_deinit_comm(), and tusb_cdc_deinit_data().
Referenced by tusb_cdc_acm_init().
tinyusb_cdc_get_intf()
esp_tusb_cdc_t * tinyusb_cdc_get_intf (int itf_num)
Return interface of a CDC device.
Parameters
itf_num
Returns
esp_tusb_cdc_t* pointer to the interface or (NULL) on error
Definition at line 18 of file cdc.c.
{
    if (itf_num >= CDC_INTF_NUM || itf_num < 0) {
        return NULL;
    }
    return cdc_obj[itf_num];
}
References CDC_INTF_NUM, and cdc_obj.
Referenced by alloc_obj(), cdc_obj_check(), free_obj(), and get_acm().
tinyusb_cdc_init()
esp_err_t tinyusb_cdc_init (int itf, const tinyusb_config_cdc_t * cfg)
Initializing CDC basic object.
Parameters
itf - number of a CDC object
cfg - CDC configuration structure
Returns
esp_err_t ESP_OK or ESP_FAIL
Definition at line 80 of file cdc.c.
{
    ESP_RETURN_ON_ERROR(cdc_obj_check(itf, false, -1), TAG, "cdc_obj_check failed");
    ESP_LOGD(TAG, "Init CDC %d", itf);
    if (cfg->cdc_class == TUSB_CLASS_CDC) {
        ESP_RETURN_ON_ERROR(tusb_cdc_comm_init(itf), TAG, "tusb_cdc_comm_init failed");
        cdc_obj[itf]->cdc_subclass.comm_subclass = cfg->cdc_subclass.comm_subclass;
    } else {
        ESP_RETURN_ON_ERROR(tusb_cdc_data_init(itf), TAG, "tusb_cdc_data_init failed");
        cdc_obj[itf]->cdc_subclass.data_subclass = cfg->cdc_subclass.data_subclass;
    }
    cdc_obj[itf]->usb_dev = cfg->usb_dev;
    return ESP_OK;
}
References tinyusb_config_cdc_t::cdc_class, cdc_obj, cdc_obj_check(), tinyusb_config_cdc_t::cdc_subclass, tinyusb_config_cdc_t::comm_subclass, tinyusb_config_cdc_t::data_subclass, ESP_LOGD, ESP_OK, ESP_RETURN_ON_ERROR, TAG, tusb_cdc_comm_init(), tusb_cdc_data_init(), and tinyusb_config_cdc_t::usb_dev.
Referenced by tusb_cdc_acm_init().