ESP-IDF Firmware: dspm::Mat Class Reference
dspm::Mat Class Reference
Matrix.
#include <mat.h>
Data Structures
struct Rect
Rectangular area.
Public Member Functions
Mat (int rows, int cols)
Mat (float *data, int rows, int cols)
Mat (float *data, int rows, int cols, int stride)
Mat ()
virtual ~Mat ()
Mat (const Mat &src)
Make copy of matrix.
Mat getROI (int startRow, int startCol, int roiRows, int roiCols)
Create a subset of matrix as ROI (Region of Interest).
Mat getROI (int startRow, int startCol, int roiRows, int roiCols, int stride)
Create a subset of matrix as ROI (Region of Interest).
Mat getROI (const Mat::Rect &rect)
Create a subset of matrix as ROI (Region of Interest).
void Copy (const Mat &src, int row_pos, int col_pos)
void CopyHead (const Mat &src)
copy header of matrix
void PrintHead (void)
print matrix header
Mat Get (int row_start, int row_size, int col_start, int col_size)
Mat Get (const Mat::Rect &rect)
Mat & operator= (const Mat &src)
float & operator() (int row, int col)
const float & operator() (int row, int col) const
Mat & operator+= (const Mat &A)
Mat & operator+= (float C)
Mat & operator-= (const Mat &A)
Mat & operator-= (float C)
Mat & operator*= (const Mat &A)
Mat & operator*= (float C)
Mat & operator/= (float C)
Mat & operator/= (const Mat &B)
Mat operator^ (int C)
void swapRows (int row1, int row2)
Mat t ()
Mat block (int startRow, int startCol, int blockRows, int blockCols)
void normalize (void)
float norm (void)
void clear (void)
Mat gaussianEliminate ()
Gaussian Elimination.
Mat rowReduceFromGaussian ()
Mat inverse ()
Mat pinv ()
float det (int n)
Static Public Member Functions
static Mat eye (int size)
static Mat ones (int size)
static Mat ones (int rows, int cols)
static Mat solve (Mat A, Mat b)
Solve the matrix.
static Mat bandSolve (Mat A, Mat b, int k)
Band solve the matrix.
static Mat roots (Mat A, Mat y)
Solve the matrix.
static float dotProduct (Mat A, Mat B)
Dotproduct of two vectors.
static Mat augment (Mat A, Mat B)
Augmented matrices.
Data Fields
int rows
int cols
int stride
int padding
float * data
int length
bool ext_buff
bool sub_matrix
Static Public Attributes
static float abs_tol = 1e-10
Private Member Functions
Mat cofactor (int row, int col, int n)
Mat adjoint ()
void allocate ()
Mat expHelper (const Mat &m, int num)
Detailed Description
Matrix.
The Mat class provides basic matrix operations on single-precision floating point values.
Definition at line 30 of file mat.h.
Constructor & Destructor Documentation
Mat() [1/5]
dspm::Mat::Mat (int rows, int cols)
Constructor allocate internal buffer.
Parameters
[in] rows amount of matrix rows
[in] cols amount of matrix columns
Definition at line 69 of file mat.cpp.
{
    ESP_LOGD("Mat", "Mat(%i, %i)", rows, cols);
    this->rows = rows;
    this->cols = cols;
    this->sub_matrix = false;
    this->stride = cols;
    this->padding = 0;
    allocate();
    memset(this->data, 0, this->length * sizeof(float));
}
References allocate(), cols, data, ESP_LOGD, length, padding, rows, stride, and sub_matrix.
Referenced by adjoint(), augment(), bandSolve(), block(), cofactor(), Copy(), CopyHead(), det(), dotProduct(), expHelper(), eye(), gaussianEliminate(), Get(), Get(), getROI(), getROI(), getROI(), inverse(), Mat(), ones(), ones(), operator*=(), operator*=(), operator+=(), operator+=(), operator-=(), operator-=(), operator/=(), operator/=(), operator=(), operator^(), pinv(), roots(), rowReduceFromGaussian(), solve(), and t().
Mat() [2/5]
dspm::Mat::Mat (float * data, int rows, int cols)
Constructor use external buffer.
Parameters
[in] data external buffer with row-major matrix data
[in] rows amount of matrix rows
[in] cols amount of matrix columns
Definition at line 81 of file mat.cpp.
{
    ESP_LOGD("Mat", "Mat(data, %i, %i)", rows, cols);
    this->rows = rows;
    this->cols = cols;
    this->sub_matrix = false;
    this->stride = cols;
    this->padding = 0;
    this->length = this->rows * this->cols;
    allocate();
    this->ext_buff = false;
    for (size_t i = 0; i < this->length; i++) {
        this->data[i] = data[i];
    }
}
References allocate(), cols, data, ESP_LOGD, ext_buff, length, padding, rows, stride, and sub_matrix.
Mat() [3/5]
dspm::Mat::Mat (float * data, int rows, int cols, int stride)
Constructor
Parameters
[in] data external buffer with row-major matrix data
[in] rows amount of matrix rows
[in] cols amount of matrix columns
[in] stride col stride
Definition at line 57 of file mat.cpp.
{
    this->rows = roi_rows;
    this->cols = roi_cols;
    this->stride = stride;
    this->padding = stride - roi_cols;
    this->length = this->rows * this->cols;
    this->sub_matrix = true;
    this->ext_buff = true;
    this->data = data;
}
References cols, data, ext_buff, length, padding, rows, stride, and sub_matrix.
Mat() [4/5]
dspm::Mat::Mat ()
Allocate matrix with undefined size.
Definition at line 98 of file mat.cpp.
{
    this->rows = 1;
    this->cols = 1;
    this->sub_matrix = false;
    this->stride = cols;
    this->padding = 0;
    ESP_LOGD("Mat", "Mat()");
    allocate();
    this->data[0] = 0;
}
References allocate(), cols, data, ESP_LOGD, padding, rows, stride, and sub_matrix.
Referenced by det().
~Mat()
dspm::Mat::~Mat () virtual
Definition at line 111 of file mat.cpp.
{
    ESP_LOGD("Mat", "~Mat(%i, %i), ext_buff=%i, data = %p", this->rows, this->cols, this->ext_buff, this->data);
    if (false == this->ext_buff) {
        delete[] data;
    }
}
References cols, data, ESP_LOGD, ext_buff, and rows.
Mat() [5/5]
dspm::Mat::Mat (const Mat & src)
Make copy of matrix.
if src matrix is sub matrix, only the header is copied if src matrix is matrix, header and data are copied
Parameters
[in] src source matrix
Definition at line 119 of file mat.cpp.
{
    this->rows = m.rows;
    this->cols = m.cols;
    this->padding = m.padding;
    this->stride = m.stride;
    this->data = m.data;
    this->sub_matrix = m.sub_matrix;
    if (m.sub_matrix) {
        this->length = m.length;
        this->data = m.data;
        this->ext_buff = true;
    } else {
        allocate();
        memcpy(this->data, m.data, this->length * sizeof(float));
    }
}
References allocate(), cols, data, ext_buff, length, m, Mat(), padding, rows, stride, and sub_matrix.
Member Function Documentation
adjoint()
Mat dspm::Mat::adjoint () private
Definition at line 783 of file mat.cpp.
{
    Mat adj(this->rows, this->cols);
    if (this->rows == 1) {
        adj(0, 0) = 1;
        return adj;
    }
    // temp is used to store cofactors of A(,)
    int sign = 1;
    Mat temp(this->rows, this->cols);
    for (int i = 0; i < this->rows; i++) {
        for (int j = 0; j < this->cols; j++) {
            // Get cofactor of A(i,j)
            temp = this->cofactor( i, j, this->rows);
            // sign of adj(j,i) positive if sum of row
            // and column indexes is even.
            sign = ((i + j) % 2 == 0) ? 1 : -1;
            // Interchanging rows and columns to get the
            // transpose of the cofactor matrix
            adj(j, i) = (sign) * (temp.det(this->rows - 1));
        }
    }
    return adj;
}
References cofactor(), cols, det(), Mat(), and rows.
Referenced by inverse().
allocate()
void dspm::Mat::allocate () private
Definition at line 834 of file mat.cpp.
{
    this->ext_buff = false;
    this->length = this->rows * this->cols;
    data = new float[this->length];
    ESP_LOGD("Mat", "allocate(%i) = %p", this->length, this->data);
}
References cols, data, ESP_LOGD, ext_buff, length, and rows.
Referenced by Mat(), Mat(), Mat(), Mat(), and operator=().
augment()
Mat dspm::Mat::augment (Mat A, Mat B) static
Augmented matrices.
Augmented matrices
Parameters
[in] A Input vector A MxN
[in] B Input vector B MxK
Returns
Augmented matrix Mx(N+K)
Definition at line 585 of file mat.cpp.
{
    Mat AB(A.rows, A.cols + B.cols);
    for (int i = 0; i < AB.rows; ++i) {
        for (int j = 0; j < AB.cols; ++j) {
            if (j < A.cols) {
                AB(i, j) = A(i, j);
            } else {
                AB(i, j) = B(i, j - A.cols);
            }
        }
    }
    return AB;
}
References A, B, cols, Mat(), and rows.
Referenced by pinv(), and roots().
bandSolve()
Mat dspm::Mat::bandSolve (Mat A, Mat b, int k) static
Band solve the matrix.
Solve band matrix. Find roots for the matrix A*x = b with bandwidth k.
Parameters
[in] A matrix [N]x[N] with input coefficients
[in] b vector [N]x[1] with result values
[in] k upper bandwidth value
Returns
matrix [N]x[1] with roots
Definition at line 514 of file mat.cpp.
{
    // optimized Gaussian elimination
    int bandsBelow = (k - 1) / 2;
    for (int i = 0; i < A.rows; ++i) {
        if (A(i, i) == 0) {
            // pivot 0 - error
            ESP_LOGW("Mat", "Error: the coefficient matrix has 0 as a pivot. Please fix the input and try again.");
            Mat err_result(b.rows, 1);
            memset(err_result.data, 0, b.rows * sizeof(float));
            return err_result;
        }
        float a_ii = 1 / A(i, i);
        for (int j = i + 1; j < A.rows && j <= i + bandsBelow; ++j) {
            int k = i + 1;
            while ((k < A.cols) && (fabs(A(j, k)) > abs_tol)) {
                A(j, k) -= A(i, k) * (A(j, i) * a_ii);
                k++;
            }
            b(j, 0) -= b(i, 0) * (A(j, i) * a_ii);
            A(j, i) = 0;
        }
    }
    // Back substitution
    Mat x(b.rows, 1);
    x((x.rows - 1), 0) = b((x.rows - 1), 0) / A((x.rows - 1), (x.rows - 1));
    for (int i = x.rows - 2; i >= 0; --i) {
        float sum = 0;
        for (int j = i + 1; j < x.rows; ++j) {
            sum += A(i, j) * x(j, 0);
        }
        x(i, 0) = (b(i, 0) - sum) / A(i, i);
    }
    return x;
}
References A, abs_tol, data, k, Mat(), rows, and x.
block()
Mat dspm::Mat::block (int startRow, int startCol, int blockRows, int blockCols)
Return part of matrix from defined position (startRow, startCol) as a matrix[blockRows x blockCols].
Parameters
[in] startRow start row position
[in] startCol start column position
[in] blockRows amount of rows in result matrix
[in] blockCols amount of columns in the result matrix
Returns
matrix [blockRows]x[blockCols]
Definition at line 433 of file mat.cpp.
{
    Mat result(blockRows, blockCols);
    for (int i = 0; i < blockRows; ++i) {
        for (int j = 0; j < blockCols; ++j) {
            result(i, j) = (*this)(startRow + i, startCol + j);
        }
    }
    return result;
}
References Mat().
clear()
void dspm::Mat::clear (void)
The method fill 0 to the matrix structure.
Definition at line 425 of file mat.cpp.
{
    for (int row = 0; row < this->rows; row++) {
        memset(this->data + (row * this->stride), 0, this->cols * sizeof(float));
    }
}
References cols, data, rows, and stride.
cofactor()
Mat dspm::Mat::cofactor (int row, int col, int n) private
Definition at line 722 of file mat.cpp.
{
    int i = 0, j = 0;
    Mat result(n, n);
    // Looping for each element of the matrix
    for (int r = 0; r < n; r++) {
        for (int c = 0; c < n; c++) {
            //  Copying into temporary matrix only those element
            //  which are not in given row and column
            if (r != row && c != col) {
                result(i, j++) = (*this)(r, c);
                // Row is filled, so increase row index and
                // reset col index
                if (j == this->rows - 1) {
                    j = 0;
                    i++;
                }
            }
        }
    }
    return result;
}
References Mat(), n, and rows.
Referenced by adjoint().
Copy()
void dspm::Mat::Copy (const Mat & src, int row_pos, int col_pos)
Make copy of matrix.
Parameters
[in] src source matrix
[in] row_pos start row position of destination matrix
[in] col_pos start col position of destination matrix
Definition at line 168 of file mat.cpp.
{
    if ((row_pos + src.rows) > this->rows) {
        return;
    }
    if ((col_pos + src.cols) > this->cols) {
        return;
    }
    for (size_t r = 0; r < src.rows; r++) {
        memcpy(&this->data[(r + row_pos) * this->stride + col_pos], &src.data[r * src.cols], src.cols * sizeof(float));
    }
}
References cols, data, Mat(), rows, and stride.
Referenced by ekf_imu13states::StateXdot(), ekf_imu13states::UpdateRefMeasurement(), ekf_imu13states::UpdateRefMeasurement(), and ekf_imu13states::UpdateRefMeasurementMagn().
CopyHead()
void dspm::Mat::CopyHead (const Mat & src)
copy header of matrix
Make a shallow copy of matrix (no data copy)
Parameters
[in] src source matrix
Definition at line 182 of file mat.cpp.
{
    if (!this->ext_buff) {
        delete[] this->data;
    }
    this->rows = src.rows;
    this->cols = src.cols;
    this->length = src.length;
    this->padding = src.padding;
    this->stride = src.stride;
    this->data = src.data;
    this->ext_buff = src.ext_buff;
    this->sub_matrix = src.sub_matrix;
}
References cols, data, ext_buff, length, Mat(), padding, rows, stride, and sub_matrix.
det()
float dspm::Mat::det (int n)
Find determinant
Parameters
[in] n element number in first row
Returns
determinant value
Definition at line 746 of file mat.cpp.
{
    //  Base case : if matrix contains single element
    if (n == 1) {
        return (*this)(0, 0);
    }
    float det = 1.0;
    Mat *temp = new Mat(n, n);
    *temp = *this;
    for (int i = 0; i < n; i++) {
        int pivot = i;
        for (int j = i + 1; j < n; j++) {
            if (std::abs((*temp)(j, i)) > std::abs((*temp)(pivot, i))) {
                pivot = j;
            }
        }
        if (pivot != i) {
            temp->swapRows(i, pivot);
            det *= -1;
        }
        if ((*temp)(i, i) == 0) {
            return 0;
        }
        det *= (*temp)(i, i);
        for (int j = i + 1; j < n; j++) {
            float factor = (*temp)(j, i) / (*temp)(i, i);
            for (int k = i + 1; k < n; k++) {
                (*temp)(j, k) -= factor * (*temp)(i, k);
            }
        }
    }
    delete temp;
    return det;
}
References det(), k, Mat(), Mat(), n, and swapRows().
Referenced by adjoint(), det(), and inverse().
dotProduct()
float dspm::Mat::dotProduct (Mat A, Mat B) static
Dotproduct of two vectors.
The method returns dotproduct of two vectors
Parameters
[in] A Input vector A Nx1
[in] B Input vector B Nx1
Returns
dotproduct value
Definition at line 576 of file mat.cpp.
{
    float sum = 0;
    for (int i = 0; i < a.rows; ++i) {
        sum += (a(i, 0) * b(i, 0));
    }
    return sum;
}
References Mat(), and rows.
expHelper()
Mat dspm::Mat::expHelper (const Mat & m, int num) private
Definition at line 842 of file mat.cpp.
{
    if (num == 0) {
        return Mat::eye(m.rows);
    } else if (num == 1) {
        return m;
    } else if (num % 2 == 0) {  // num is even
        return expHelper(m * m, num / 2);
    } else {                    // num is odd
        return m * expHelper(m * m, (num - 1) / 2);
    }
}
References expHelper(), eye(), m, and Mat().
Referenced by expHelper(), and operator^().
eye()
Mat dspm::Mat::eye (int size) static
Create identity matrix. Create a square matrix and fill diagonal with 1.
Parameters
[in] size matrix size
Returns
matrix [N]x[N] with 1 in diagonal
Definition at line 394 of file mat.cpp.
{
    Mat temp(size, size);
    for (int i = 0; i < temp.rows; ++i) {
        for (int j = 0; j < temp.cols; ++j) {
            if (i == j) {
                temp(i, j) = 1;
            } else {
                temp(i, j) = 0;
            }
        }
    }
    return temp;
}
References cols, Mat(), and rows.
Referenced by ekf::CovariancePrediction(), dispaly_esp_text(), dispaly_esp_text(), dispaly_esp_text(), dispaly_esp_text(), draw_3d_image(), draw_3d_image(), draw_3d_image(), draw_3d_image(), draw_3d_image_task(), draw_3d_image_task(), draw_3d_image_task(), draw_3d_image_task(), draw_3d_image_task(), draw_3d_image_task(), draw_3d_image_task(), draw_3d_image_task(), expHelper(), ekf_imu13states::Init(), ekf_imu13states::LinearizeFG(), pinv(), ekf_imu13states::TestFull(), ekf::UpdateRef(), ekf_imu13states::UpdateRefMeasurement(), and ekf_imu13states::UpdateRefMeasurementMagn().
gaussianEliminate()
Mat dspm::Mat::gaussianEliminate ()
Gaussian Elimination.
Gaussian Elimination of matrix
Returns
result matrix
Definition at line 600 of file mat.cpp.
{
    Mat Ab(*this);
    int rows = Ab.rows;
    int cols = Ab.cols;
    int Acols = cols - 1;
    int i = 0; // row tracker
    int j = 0; // column tracker
    // iterate through the rows
    while (i < rows) {
        // find a pivot for the row
        bool pivot_found = false;
        while (j < Acols && !pivot_found) {
            if (Ab(i, j) != 0) { // pivot not equal to 0
                pivot_found = true;
            } else { // check for a possible swap
                int max_row = i;
                float max_val = 0;
                for (int k = i + 1; k < rows; ++k) {
                    float cur_abs = Ab(k, j) >= 0 ? Ab(k, j) : -1 * Ab(k, j);
                    if (cur_abs > max_val) {
                        max_row = k;
                        max_val = cur_abs;
                    }
                }
                if (max_row != i) {
                    Ab.swapRows(max_row, i);
                    pivot_found = true;
                } else {
                    j++;
                }
            }
        }
        // perform elimination as normal if pivot was found
        if (pivot_found) {
            for (int t = i + 1; t < rows; ++t) {
                for (int s = j + 1; s < cols; ++s) {
                    Ab(t, s) = Ab(t, s) - Ab(i, s) * (Ab(t, j) / Ab(i, j));
                    if (Ab(t, s) < abs_tol && Ab(t, s) > -1 * abs_tol) {
                        Ab(t, s) = 0;
                    }
                }
                Ab(t, j) = 0;
            }
        }
        i++;
        j++;
    }
    return Ab;
}
References abs_tol, cols, k, Mat(), rows, swapRows(), and t().
Referenced by pinv().
Get() [1/2]
Mat dspm::Mat::Get (const Mat::Rect & rect)
Make copy of matrix.
Parameters
[in] rect rectangular area of interest
Returns
result matrix size row_size x col_size
Definition at line 226 of file mat.cpp.
{
    return (Get(rect.y, rect.height, rect.x, rect.width));
}
References Get(), dspm::Mat::Rect::height, Mat(), dspm::Mat::Rect::width, dspm::Mat::Rect::x, and dspm::Mat::Rect::y.
Get() [2/2]
Mat dspm::Mat::Get (int row_start, int row_size, int col_start, int col_size)
Make copy of matrix.
Parameters
[in] row_start start row position of source matrix to copy
[in] row_size size of wor elements of source matrix to copy
[in] col_start start col position of source matrix to copy
[in] col_size size of wor elements of source matrix to copy
Returns
result matrix size row_size x col_size
Definition at line 209 of file mat.cpp.
{
    Mat result(row_size, col_size);
    if ((row_start + row_size) > this->rows) {
        return result;
    }
    if ((col_start + col_size) > this->cols) {
        return result;
    }
    for (size_t r = 0; r < result.rows; r++) {
        memcpy(&result.data[r * result.cols], &this->data[(r + row_start) * this->stride + col_start], result.cols * sizeof(float));
    }
    return result;
}
References cols, data, Mat(), and rows.
Referenced by Get(), ekf_imu13states::LinearizeFG(), and operator*=().
getROI() [1/3]
Mat dspm::Mat::getROI (const Mat::Rect & rect)
Create a subset of matrix as ROI (Region of Interest).
Parameters
[in] rect rectangular area of interest
Returns
result matrix size rect.rectRows x rect.rectCols
Definition at line 158 of file mat.cpp.
{
    return (getROI(rect.y, rect.x, rect.height, rect.width, this->cols));
}
References getROI(), dspm::Mat::Rect::height, Mat(), dspm::Mat::Rect::width, dspm::Mat::Rect::x, and dspm::Mat::Rect::y.
getROI() [2/3]
Mat dspm::Mat::getROI (int startRow, int startCol, int roiRows, int roiCols)
Create a subset of matrix as ROI (Region of Interest).
Parameters
[in] startRow start row position of source matrix to get the subset matrix from
[in] startCol start col position of source matrix to get the subset matrix from
[in] roiRows size of row elements of source matrix to get the subset matrix from
[in] roiCols size of col elements of source matrix to get the subset matrix from
Returns
result matrix size roiRows x roiCols
Definition at line 163 of file mat.cpp.
{
    return (getROI(startRow, startCol, roiRows, roiCols, this->cols));
}
References cols, getROI(), and Mat().
Referenced by getROI(), and getROI().
getROI() [3/3]
Mat dspm::Mat::getROI (int startRow, int startCol, int roiRows, int roiCols, int stride)
Create a subset of matrix as ROI (Region of Interest).
Parameters
[in] startRow start row position of source matrix to get the subset matrix from
[in] startCol start col position of source matrix to get the subset matrix from
[in] roiRows size of row elements of source matrix to get the subset matrix from
[in] roiCols size of col elements of source matrix to get the subset matrix from
[in] stride number of cols + padding between 2 rows
Returns
result matrix size roiRows x roiCols
Definition at line 138 of file mat.cpp.
{
    Mat result(this->data, roiRows, roiCols, 0);
    if ((startRow + roiRows) > this->rows) {
        return result;
    }
    if ((startCol + roiCols) > this->cols) {
        return result;
    }
    const int ptr_move = startRow * this->cols + startCol;
    float *new_data_ptr = this->data + ptr_move;
    result.data = new_data_ptr;
    result.stride = stride;
    result.padding = result.stride - result.cols;
    return result;
}
References cols, data, Mat(), padding, rows, and stride.
inverse()
Mat dspm::Mat::inverse ()
Find the inverse matrix
Returns
inverse matrix
Definition at line 812 of file mat.cpp.
{
    Mat result(this->rows, this->cols);
    // Find determinant of matrix
    float det = this->det(this->rows);
    if (det == 0) {
        //std::cout << "Singular matrix, can't find its inverse";
        return result;
    }
    // Find adjoint
    Mat adj = this->adjoint();
    // Find Inverse using formula "inverse(A) = adj(A)/det(A)"
    for (int i = 0; i < this->rows; i++)
        for (int j = 0; j < this->cols; j++) {
            result(i, j) = adj(i, j) / float(det);
        }
    return result;
}
References adjoint(), cols, det(), Mat(), and rows.
norm()
float dspm::Mat::norm (void)
Return norm of the vector. If it's matrix, calculate matrix norm
Returns
matrix norm
Definition at line 456 of file mat.cpp.
{
    float sqr_norm = 0;
    for (int i = 0; i < this->rows; ++i) {
        for (int j = 0; j < this->cols; ++j) {
            sqr_norm += (*this)(i, j) * (*this)(i, j);
        }
    }
    sqr_norm = sqrtf(sqr_norm);
    return sqr_norm;
}
References cols, and rows.
Referenced by draw_3d_image_task(), draw_3d_image_task(), kalman_filter_task(), kalman_filter_task(), kalman_filter_task(), kalman_filter_task(), ekf::rotm2quat(), ekf_imu13states::TestFull(), ekf_imu13states::UpdateRefMeasurement(), ekf_imu13states::UpdateRefMeasurement(), and ekf_imu13states::UpdateRefMeasurementMagn().
normalize()
void dspm::Mat::normalize (void)
Normalizes the vector, i.e. divides it by its own norm. If it's matrix, calculate matrix norm
Definition at line 444 of file mat.cpp.
{
    float sqr_norm = 0;
    for (int i = 0; i < this->rows; ++i) {
        for (int j = 0; j < this->cols; ++j) {
            sqr_norm += (*this)(i, j) * (*this)(i, j);
        }
    }
    sqr_norm = 1 / sqrtf(sqr_norm);
    *this *= sqr_norm;
}
References cols, and rows.
ones() [1/2]
Mat dspm::Mat::ones (int rows, int cols) static
Create matrix with all elements 1. Create a matrix and fill all elements with 1.
Parameters
[in] rows matrix rows
[in] cols matrix cols
Returns
matrix [N]x[N] with 1 in all elements
Definition at line 414 of file mat.cpp.
{
    Mat temp(rows, cols);
    for (int row = 0; row < temp.rows; ++row) {
        for (int col = 0; col < temp.cols; ++col) {
            temp(row, col) = 1;
        }
    }
    return temp;
}
References cols, Mat(), and rows.
ones() [2/2]
Mat dspm::Mat::ones (int size) static
Create matrix with all elements 1. Create a square matrix and fill all elements with 1.
Parameters
[in] size matrix size
Returns
matrix [N]x[N] with 1 in all elements
Definition at line 409 of file mat.cpp.
{
    return (ones(size, size));
}
References Mat(), and ones().
Referenced by ones().
operator()() [1/2]
float & dspm::Mat::operator() (int row, int col) inline
Access to the matrix elements.
Parameters
[in] row row position
[in] col column position
Returns
element of matrix M[row][col]
Definition at line 218 of file mat.h.
    {
        return data[row * this->stride + col];
    }
References data.
operator()() [2/2]
const float & dspm::Mat::operator() (int row, int col) const inline
Access to the matrix elements.
Parameters
[in] row row position
[in] col column position
Returns
element of matrix M[row][col]
Definition at line 230 of file mat.h.
    {
        return data[row * this->stride + col];
    }
References data.
operator*=() [1/2]
Mat & dspm::Mat::operator*= (const Mat & A)
*= operator The operator use DSP optimized implementation of multiplication.
Parameters
[in] A source matrix
Returns
result matrix: result -= A
Definition at line 312 of file mat.cpp.
{
    if (this->cols != m.rows) {
        ESP_LOGW("Mat", "operator *= Error: matrices do not have equal dimensions");
        return *this;
    }
    if (this->sub_matrix || m.sub_matrix) {
        Mat temp = this->Get(0, this->rows, 0, this->cols);
        dspm_mult_ex_f32(temp.data, m.data, this->data, temp.rows, temp.cols, m.cols, temp.padding, m.padding, this->padding);
    } else {
        Mat temp = *this;
        dspm_mult_f32(temp.data, m.data, this->data, temp.rows, temp.cols, m.cols);
    }
    return (*this);
}
References cols, data, dspm_mult_ex_f32, dspm_mult_f32, Get(), m, Mat(), padding, rows, and sub_matrix.
operator*=() [2/2]
Mat & dspm::Mat::operator*= (float C)
+= with constant operator The operator use DSP optimized implementation of multiplication.
Parameters
[in] C constant value
Returns
result matrix: result *= C
Definition at line 329 of file mat.cpp.
{
    if (this->sub_matrix) {
        dspm_mulc_f32(this->data, this->data, num, this->rows, this->cols, this->padding, this->padding, 1, 1);
    } else {
        dsps_mulc_f32_ansi(this->data, this->data, this->length, num, 1, 1);
    }
    return *this;
}
References cols, data, dspm_mulc_f32, dsps_mulc_f32_ansi(), length, Mat(), padding, rows, and sub_matrix.
operator+=() [1/2]
Mat & dspm::Mat::operator+= (const Mat & A)
+= operator The operator use DSP optimized implementation of multiplication.
Parameters
[in] A source matrix
Returns
result matrix: result += A
Definition at line 262 of file mat.cpp.
{
    if ((this->rows != m.rows) || (this->cols != m.cols)) {
        ESP_LOGW("Mat", "operator += Error: matrices do not have equal dimensions");
        return *this;
    }
    if (this->sub_matrix || m.sub_matrix) {
        dspm_add_f32(this->data, m.data, this->data, this->rows, this->cols, this->padding, m.padding, this->padding, 1, 1, 1);
    } else {
        dsps_add_f32(this->data, m.data, this->data, this->length, 1, 1, 1);
    }
    return *this;
}
References data, dspm_add_f32, dsps_add_f32, m, Mat(), rows, and sub_matrix.
operator+=() [2/2]
Mat & dspm::Mat::operator+= (float C)
+= operator The operator use DSP optimized implementation of multiplication.
Parameters
[in] C constant
Returns
result matrix: result += C
Definition at line 277 of file mat.cpp.
{
    if (this->sub_matrix) {
        dspm_addc_f32(this->data, this->data, C, this->rows, this->cols, this->padding, this->padding, 1, 1);
    } else {
        dsps_addc_f32_ansi(this->data, this->data, this->length, C, 1, 1);
    }
    return *this;
}
References C, cols, data, dspm_addc_f32, dsps_addc_f32_ansi(), length, Mat(), padding, rows, and sub_matrix.
operator-=() [1/2]
Mat & dspm::Mat::operator-= (const Mat & A)
-= operator The operator use DSP optimized implementation of multiplication.
Parameters
[in] A source matrix
Returns
result matrix: result -= A
Definition at line 287 of file mat.cpp.
{
    if ((this->rows != m.rows) || (this->cols != m.cols)) {
        ESP_LOGW("Mat", "operator -= Error: matrices do not have equal dimensions");
        return *this;
    }
    if (this->sub_matrix || m.sub_matrix) {
        dspm_sub_f32(this->data, m.data, this->data, this->rows, this->cols, this->padding, m.padding, this->padding, 1, 1, 1);
    } else {
        dsps_sub_f32(this->data, m.data, this->data, this->length, 1, 1, 1);
    }
    return *this;
}
References data, dspm_sub_f32, dsps_sub_f32, m, Mat(), rows, and sub_matrix.
operator-=() [2/2]
Mat & dspm::Mat::operator-= (float C)
-= operator The operator use DSP optimized implementation of multiplication.
Parameters
[in] C constant
Returns
result matrix: result -= C
Definition at line 302 of file mat.cpp.
{
    if (this->sub_matrix) {
        dspm_addc_f32(this->data, this->data, -C, this->rows, this->cols, this->padding, this->padding, 1, 1);
    } else {
        dsps_addc_f32_ansi(this->data, this->data, this->length, -C, 1, 1);
    }
    return *this;
}
References C, cols, data, dspm_addc_f32, dsps_addc_f32_ansi(), length, Mat(), padding, rows, and sub_matrix.
operator/=() [1/2]
Mat & dspm::Mat::operator/= (const Mat & B)
/= operator
Parameters
[in] B source matrix
Returns
result matrix: result[i,j] = result[i,j]/B[i,j]
Definition at line 339 of file mat.cpp.
{
    if ((this->rows != B.rows) || (this->cols != B.cols)) {
        ESP_LOGW("Mat", "operator /= Error: matrices do not have equal dimensions");
        return *this;
    }
    for (int row = 0; row < this->rows; row++) {
        for (int col = 0; col < this->cols; col++) {
            (*this)(row, col) = (*this)(row, col) / B(row, col);
        }
    }
    return (*this);
}
References B, cols, Mat(), and rows.
operator/=() [2/2]
Mat & dspm::Mat::operator/= (float C)
/= with constant operator The operator use DSP optimized implementation of multiplication.
Parameters
[in] C constant value
Returns
result matrix: result /= C
Definition at line 354 of file mat.cpp.
{
    if (this->sub_matrix) {
        dspm_mulc_f32(this->data, this->data, 1 / num, this->rows, this->cols, this->padding, this->padding, 1, 1);
    } else {
        dsps_mulc_f32_ansi(this->data, this->data, this->length, 1 / num, 1, 1);
    }
    return *this;
}
References cols, data, dspm_mulc_f32, dsps_mulc_f32_ansi(), length, Mat(), padding, rows, and sub_matrix.
operator=()
Mat & dspm::Mat::operator= (const Mat & src)
Copy operator
Parameters
[in] src source matrix
Returns
matrix copy
Definition at line 231 of file mat.cpp.
{
    if (this == &m) {
        return *this;
    }
    // matrix dimensions not equal
    if (this->rows != m.rows || this->cols != m.cols) {
        // left operand is a sub-matrix - error
        if (this->sub_matrix) {
            ESP_LOGE("Mat", "operator = Error for sub-matrices: operands matrices dimensions %dx%d and %dx%d do not match", this->rows, this->cols, m.rows, m.cols);
            return *this;
        }
        if (!this->ext_buff) {
            delete[] this->data;
        }
        this->ext_buff = false;
        this->rows = m.rows;
        this->cols = m.cols;
        this->stride = this->cols;
        this->padding = 0;
        this->sub_matrix = false;
        allocate();
    }
    for (int row = 0; row < this->rows; row++) {
        memcpy(this->data + (row * this->stride), m.data + (row * m.stride), this->cols * sizeof(float));
    }
    return *this;
}
References allocate(), cols, data, ext_buff, m, Mat(), padding, rows, stride, and sub_matrix.
operator^()
Mat dspm::Mat::operator^ (int C)
^= xor with constant operator The operator use DSP optimized implementation of multiplication.
Parameters
[in] C constant value
Returns
result matrix: result ^= C
Definition at line 364 of file mat.cpp.
{
    Mat temp(*this);
    return expHelper(temp, num);
}
References expHelper(), and Mat().
pinv()
Mat dspm::Mat::pinv ()
Find pseudo inverse matrix
Returns
inverse matrix
Definition at line 707 of file mat.cpp.
{
    Mat I = Mat::eye(this->rows);
    Mat AI = Mat::augment(*this, I);
    Mat U = AI.gaussianEliminate();
    Mat IAInverse = U.rowReduceFromGaussian();
    Mat AInverse(this->rows, this->cols);
    for (int i = 0; i < this->rows; ++i) {
        for (int j = 0; j < this->cols; ++j) {
            AInverse(i, j) = IAInverse(i, j + this->cols);
        }
    }
    return AInverse;
}
References augment(), cols, eye(), gaussianEliminate(), Mat(), rowReduceFromGaussian(), and rows.
Referenced by ekf::UpdateRef().
PrintHead()
void dspm::Mat::PrintHead (void)
print matrix header
Print all information about matrix to the terminal
Parameters
[in] src source matrix
Definition at line 197 of file mat.cpp.
{
    std::cout << "rows     " << this->rows << std::endl;
    std::cout << "cols     " << this->cols << std::endl;
    std::cout << "lenght   " << this->length << std::endl;
    std::cout << "data     " << this->data << std::endl;
    std::cout << "ext_buff " << this->ext_buff << std::endl;
    std::cout << "sub_mat  " << this->sub_matrix << std::endl;
    std::cout << "stride   " << this->stride << std::endl;
    std::cout << "padding  " << this->padding << std::endl << std::endl;
}
References cols, data, ext_buff, length, padding, rows, stride, and sub_matrix.
roots()
Mat dspm::Mat::roots (Mat A, Mat y) static
Solve the matrix.
Different way to solve the matrix. Find roots for the matrix A*x = y
Parameters
[in] A matrix [N]x[N] with input coefficients
[in] y vector [N]x[1] with result values
Returns
matrix [N]x[1] with roots
Definition at line 552 of file mat.cpp.
{
    int n = A.cols + 1;
    Mat result(y.rows, 1);
    Mat g_m = Mat::augment(A, y);
    for (int j = 0; j < A.cols; j++) {
        float g_jj = 1 / g_m(j, j);
        for (int i = 0; i < A.cols; i++) {
            if (i != j) {
                float c = g_m(i, j) * g_jj;
                for (int k = 0; k < n; k++) {
                    g_m(i, k) = g_m(i, k) - c * g_m(j, k);
                }
            }
        }
    }
    for (int i = 0; i < A.rows; i++) {
        result(i, 0) = g_m(i, A.cols) / g_m(i, i);
    }
    return result;
}
References A, augment(), k, Mat(), n, and y.
rowReduceFromGaussian()
Mat dspm::Mat::rowReduceFromGaussian ()
Row reduction for Gaussian elimination
Returns
result matrix
Definition at line 656 of file mat.cpp.
{
    Mat R(*this);
    int rows = R.rows;
    int cols = R.cols;
    int i = rows - 1; // row tracker
    int j = cols - 2; // column tracker
    // iterate through every row
    while (i >= 0) {
        // find the pivot column
        int k = j - 1;
        while (k >= 0) {
            if (R(i, k) != 0) {
                j = k;
            }
            k--;
        }
        // zero out elements above pivots if pivot not 0
        if (R(i, j) != 0) {
            for (int t = i - 1; t >= 0; --t) {
                for (int s = 0; s < cols; ++s) {
                    if (s != j) {
                        R(t, s) = R(t, s) - R(i, s) * (R(t, j) / R(i, j));
                        if (R(t, s) < abs_tol && R(t, s) > -1 * abs_tol) {
                            R(t, s) = 0;
                        }
                    }
                }
                R(t, j) = 0;
            }
            // divide row by pivot
            for (int k = j + 1; k < cols; ++k) {
                R(i, k) = R(i, k) / R(i, j);
                if (R(i, k) < abs_tol && R(i, k) > -1 * abs_tol) {
                    R(i, k) = 0;
                }
            }
            R(i, j) = 1;
        }
        i--;
        j--;
    }
    return R;
}
References abs_tol, cols, k, Mat(), rows, and t().
Referenced by pinv().
solve()
Mat dspm::Mat::solve (Mat A, Mat b) static
Solve the matrix.
Solve matrix. Find roots for the matrix A*x = b
Parameters
[in] A matrix [N]x[N] with input coefficients
[in] b vector [N]x[1] with result values
Returns
matrix [N]x[1] with roots
Definition at line 468 of file mat.cpp.
{
    // Gaussian elimination
    for (int i = 0; i < A.rows; ++i) {
        if (A(i, i) == 0) {
            // pivot 0 - error
            ESP_LOGW("Mat", "Error: the coefficient matrix has 0 as a pivot. Please fix the input and try again.");
            Mat err_result(0, 0);
            return err_result;
        }
        float a_ii = 1 / A(i, i);
        for (int j = i + 1; j < A.rows; ++j) {
            float a_ji = A(j, i) * a_ii;
            for (int k = i + 1; k < A.cols; ++k) {
                A(j, k) -= A(i, k) * a_ji;
                if ((A(j, k) < abs_tol) && (A(j, k) > -1 * abs_tol)) {
                    A(j, k) = 0;
                }
            }
            b(j, 0) -= b(i, 0) * a_ji;
            if (A(j, 0) < abs_tol && A(j, 0) > -1 * abs_tol) {
                A(j, 0) = 0;
            }
            A(j, i) = 0;
        }
    }
    // Back substitution
    Mat x(b.rows, 1);
    x((x.rows - 1), 0) = b((x.rows - 1), 0) / A((x.rows - 1), (x.rows - 1));
    if (x((x.rows - 1), 0) < abs_tol && x((x.rows - 1), 0) > -1 * abs_tol) {
        x((x.rows - 1), 0) = 0;
    }
    for (int i = x.rows - 2; i >= 0; --i) {
        float sum = 0;
        for (int j = i + 1; j < x.rows; ++j) {
            sum += A(i, j) * x(j, 0);
        }
        x(i, 0) = (b(i, 0) - sum) / A(i, i);
        if (x(i, 0) < abs_tol && x(i, 0) > -1 * abs_tol) {
            x(i, 0) = 0;
        }
    }
    return x;
}
References A, abs_tol, k, Mat(), rows, and x.
swapRows()
void dspm::Mat::swapRows (int row1, int row2)
Swap two rows between each other.
Parameters
[in] row1 position of first row
[in] row2 position of second row
Definition at line 370 of file mat.cpp.
{
    if ((this->rows <= r1) || (this->rows <= r2)) {
        ESP_LOGW("Mat", "swapRows Error: row %d or %d out of matrix row %d range", r1, r2, this->rows);
    } else {
        for (int i = 0; i < this->cols; i++) {
            float temp = this->data[r1 * this->stride + i];
            this->data[r1 * this->stride + i] = this->data[r2 * this->stride + i];
            this->data[r2 * this->stride + i] = temp;
        }
    }
}
References cols, data, rows, and stride.
Referenced by det(), and gaussianEliminate().
t()
Mat dspm::Mat::t ()
Matrix transpose. Change rows and columns between each other.
Returns
transposed matrix
Definition at line 383 of file mat.cpp.
{
    Mat ret(this->cols, this->rows);
    for (int i = 0; i < this->rows; ++i) {
        for (int j = 0; j < this->cols; ++j) {
            ret(j, i) = this->data[i * this->stride + j];
        }
    }
    return ret;
}
References cols, data, Mat(), rows, and stride.
Referenced by ekf::CovariancePrediction(), draw_3d_image_task(), draw_3d_image_task(), gaussianEliminate(), rowReduceFromGaussian(), ekf_imu13states::TestFull(), update_rotation_matrix(), ekf::UpdateRef(), ekf_imu13states::UpdateRefMeasurement(), ekf_imu13states::UpdateRefMeasurement(), and ekf_imu13states::UpdateRefMeasurementMagn().
Field Documentation
abs_tol
float dspm::Mat::abs_tol = 1e-10 static
Max acceptable absolute tolerance
Definition at line 39 of file mat.h.
Referenced by bandSolve(), gaussianEliminate(), rowReduceFromGaussian(), and solve().
cols
int dspm::Mat::cols
Amount of columns
Definition at line 34 of file mat.h.
Referenced by adjoint(), allocate(), augment(), clear(), Copy(), CopyHead(), draw_3d_image(), draw_3d_image(), draw_3d_image(), draw_3d_image(), eye(), gaussianEliminate(), Get(), getROI(), getROI(), init_perspective_matrix(), inverse(), Mat(), Mat(), Mat(), Mat(), Mat(), norm(), normalize(), ones(), dspm::operator*(), operator*=(), operator*=(), dspm::operator+(), operator+=(), dspm::operator-(), operator-=(), operator/=(), operator/=(), operator=(), dspm::operator==(), pinv(), print_matrix(), PrintHead(), rowReduceFromGaussian(), swapRows(), t(), update_perspective_matrix(), update_rotation_matrix(), and ~Mat().
data
float* dspm::Mat::data
Buffer with matrix data
Definition at line 37 of file mat.h.
Referenced by allocate(), bandSolve(), clear(), Copy(), CopyHead(), ekf::dFdq(), ekf::dFdq_inv(), draw_3d_image(), draw_3d_image(), draw_3d_image(), draw_3d_image(), draw_3d_image_task(), draw_3d_image_task(), Get(), getROI(), kalman_filter_calibration(), kalman_filter_calibration(), kalman_filter_calibration(), kalman_filter_calibration(), kalman_filter_task(), kalman_filter_task(), kalman_filter_task(), kalman_filter_task(), ekf_imu13states::LinearizeFG(), Mat(), Mat(), Mat(), Mat(), Mat(), operator()(), operator()(), dspm::operator*(), dspm::operator*(), operator*=(), operator*=(), dspm::operator+(), dspm::operator+(), operator+=(), operator+=(), dspm::operator-(), dspm::operator-(), operator-=(), operator-=(), dspm::operator/(), operator/=(), operator=(), PrintHead(), ekf::qProduct(), ekf::quat2eul(), ekf::SkewSym4x4(), swapRows(), t(), ekf_imu13states::TestFull(), update_rotation_matrix(), ekf_imu13states::UpdateRefMeasurement(), ekf_imu13states::UpdateRefMeasurement(), ekf_imu13states::UpdateRefMeasurementMagn(), and ~Mat().
ext_buff
bool dspm::Mat::ext_buff
Flag indicates that matrix use external buffer
Definition at line 40 of file mat.h.
Referenced by allocate(), CopyHead(), Mat(), Mat(), Mat(), operator=(), PrintHead(), and ~Mat().
length
int dspm::Mat::length
Total amount of data in data array
Definition at line 38 of file mat.h.
Referenced by allocate(), CopyHead(), Mat(), Mat(), Mat(), Mat(), operator*=(), operator+=(), operator-=(), operator/=(), and PrintHead().
padding
int dspm::Mat::padding
Padding between 2 rows
Definition at line 36 of file mat.h.
Referenced by CopyHead(), getROI(), Mat(), Mat(), Mat(), Mat(), Mat(), dspm::operator*(), dspm::operator*(), operator*=(), operator*=(), dspm::operator+(), dspm::operator+(), operator+=(), dspm::operator-(), dspm::operator-(), operator-=(), dspm::operator/(), operator/=(), operator=(), and PrintHead().
rows
int dspm::Mat::rows
Amount of rows
Definition at line 33 of file mat.h.
Referenced by adjoint(), allocate(), augment(), bandSolve(), clear(), cofactor(), Copy(), CopyHead(), dispaly_esp_text(), dispaly_esp_text(), dispaly_esp_text(), dispaly_esp_text(), display_3d_image(), display_3d_image(), display_3d_image(), display_3d_image(), display_3d_image(), display_3d_image(), display_3d_image(), display_3d_image(), display_3d_image(), display_3d_image(), dotProduct(), draw_3d_image(), draw_3d_image(), draw_3d_image(), draw_3d_image(), eye(), gaussianEliminate(), Get(), getROI(), init_perspective_matrix(), inverse(), Mat(), Mat(), Mat(), Mat(), Mat(), norm(), normalize(), ones(), dspm::operator*(), operator*=(), operator*=(), dspm::operator+(), operator+=(), operator+=(), dspm::operator-(), operator-=(), operator-=(), operator/=(), operator/=(), operator=(), dspm::operator==(), pinv(), print_matrix(), PrintHead(), rowReduceFromGaussian(), solve(), swapRows(), t(), ekf::Update(), update_perspective_matrix(), update_rotation_matrix(), ekf::UpdateRef(), and ~Mat().
stride
int dspm::Mat::stride
Stride = (number of elements in a row) + padding
Definition at line 35 of file mat.h.
Referenced by clear(), Copy(), CopyHead(), getROI(), Mat(), Mat(), Mat(), Mat(), Mat(), operator=(), PrintHead(), swapRows(), and t().
sub_matrix
bool dspm::Mat::sub_matrix
Flag indicates that matrix is a subset of another matrix
Definition at line 41 of file mat.h.
Referenced by CopyHead(), Mat(), Mat(), Mat(), Mat(), Mat(), dspm::operator*(), operator*=(), operator*=(), dspm::operator+(), operator+=(), operator+=(), dspm::operator-(), operator-=(), operator-=(), operator/=(), operator=(), and PrintHead().
The documentation for this class was generated from the following files:
mat.h
mat.cpp