ESP-IDF Firmware: ekf Class Reference
ekf Class Reference abstract
#include <ekf.h>
Public Member Functions
ekf (int x, int w)
virtual ~ekf ()
virtual void Process (float *u, float dt)
virtual void Init ()=0
void RungeKutta (dspm::Mat &x, float *u, float dt)
virtual dspm::Mat StateXdot (dspm::Mat &x, float *u)
virtual void LinearizeFG (dspm::Mat &x, float *u)=0
virtual void CovariancePrediction (float dt)
virtual void Update (dspm::Mat &H, float *measured, float *expected, float *R)
virtual void UpdateRef (dspm::Mat &H, float *measured, float *expected, float *R)
Static Public Member Functions
static dspm::Mat quat2rotm (float q[4])
static dspm::Mat rotm2quat (dspm::Mat &R)
static dspm::Mat quat2eul (const float q[4])
static dspm::Mat eul2rotm (float xyz[3])
static dspm::Mat rotm2eul (dspm::Mat &rotm)
static dspm::Mat dFdq (dspm::Mat &vector, dspm::Mat &quat)
static dspm::Mat dFdq_inv (dspm::Mat &vector, dspm::Mat &quat)
static dspm::Mat SkewSym4x4 (float *w)
static dspm::Mat qProduct (float *q)
Data Fields
int NUMX
int NUMW
dspm::Mat & X
dspm::Mat & F
dspm::Mat & G
dspm::Mat & P
dspm::Mat & Q
float * HP
float * Km
Detailed Description
The ekf is a base class for Extended Kalman Filter. It contains main matrix operations and define the processing flow.
Definition at line 29 of file ekf.h.
Constructor & Destructor Documentation
ekf()
ekf::ekf (int x, int w)
Constructor of EKF. THe constructor allocate main memory for the matrixes.
Parameters
[in] x - amount of states in EKF. x[n] = F*x[n-1] + G*u + W. Size of matrix F
[in] w - amount of control measurements and noise inputs. Size of matrix G
Definition at line 19 of file ekf.cpp.
                     : NUMX(x),
    NUMW(w),
    X(*new dspm::Mat(x, 1)),
    F(*new dspm::Mat(x, x)),
    G(*new dspm::Mat(x, w)),
    P(*new dspm::Mat(x, x)),
    Q(*new dspm::Mat(w, w))
{
    this->P *= 0;
    this->Q *= 0;
    this->X *= 0;
    this->X.data[0] = 1; // direction to 0
    this->HP = new float[this->NUMX];
    this->Km = new float[this->NUMX];
    for (size_t i = 0; i < this->NUMX; i++) {
        this->HP[i] = 0;
        this->Km[i] = 0;
    }
}
References F, G, HP, Km, NUMW, NUMX, P, Q, X, and x.
Referenced by ekf_imu13states::ekf_imu13states().
~ekf()
ekf::~ekf () virtual
Distructor of EKF
Definition at line 41 of file ekf.cpp.
{
    delete &X;
    delete &F;
    delete &G;
    delete &P;
    delete &Q;
    delete this->HP;
    delete this->Km;
}
References F, G, HP, Km, P, Q, and X.
Member Function Documentation
CovariancePrediction()
void ekf::CovariancePrediction (float dt) virtual
Calculates covariance prediction matrux P. Update matrix P
Parameters
[in] dt time interval from last update
Definition at line 139 of file ekf.cpp.
{
    dspm::Mat f = this->F * dt;
    f = f + dspm::Mat::eye(this->NUMX);
    dspm::Mat f_t = f.t();
    this->P = ((f * this->P) * f_t) + (dt * dt) * ((G * Q) * G.t());
}
References dspm::Mat::eye(), F, G, NUMX, P, Q, and dspm::Mat::t().
Referenced by Process().
dFdq()
dspm::Mat ekf::dFdq (dspm::Mat & vector, dspm::Mat & quat) static
Df/dq: Derivative of vector by quaternion.
Parameters
[in] vector input vector
[in] quat quaternion
Returns
Derivative matrix 3x4
Definition at line 367 of file ekf.cpp.
{
    dspm::Mat result(3, 4);
    result(0, 0) = q.data[0] * vector.data[0] - q.data[3] * vector.data[1] + q.data[2] * vector.data[2];
    result(0, 1) = q.data[1] * vector.data[0] + q.data[2] * vector.data[1] + q.data[3] * vector.data[2];
    result(0, 2) = -q.data[2] * vector.data[0] + q.data[1] * vector.data[1] + q.data[0] * vector.data[2];
    result(0, 3) = -q.data[3] * vector.data[0] - q.data[0] * vector.data[1] + q.data[1] * vector.data[2];
    result(1, 0) = q.data[3] * vector.data[0] + q.data[0] * vector.data[1] - q.data[1] * vector.data[2];
    result(1, 1) = q.data[2] * vector.data[0] - q.data[1] * vector.data[1] - q.data[0] * vector.data[2];
    result(1, 2) = q.data[1] * vector.data[0] + q.data[2] * vector.data[1] + q.data[3] * vector.data[2];
    result(1, 3) = q.data[0] * vector.data[0] - q.data[3] * vector.data[1] + q.data[2] * vector.data[2];
    result(2, 0) = -q.data[2] * vector.data[0] + q.data[1] * vector.data[1] + q.data[0] * vector.data[2];
    result(2, 1) = q.data[3] * vector.data[0] + q.data[0] * vector.data[1] - q.data[1] * vector.data[2];
    result(2, 2) = -q.data[0] * vector.data[0] + q.data[3] * vector.data[1] - q.data[2] * vector.data[2];
    result(2, 3) = q.data[1] * vector.data[0] + q.data[2] * vector.data[1] + q.data[3] * vector.data[2];
    result *= 2;
    return result;
}
References dspm::Mat::data.
dFdq_inv()
dspm::Mat ekf::dFdq_inv (dspm::Mat & vector, dspm::Mat & quat) static
Df/dq: Derivative of vector by inverted quaternion.
Parameters
[in] vector input vector
[in] quat quaternion
Returns
Derivative matrix 3x4
Definition at line 389 of file ekf.cpp.
{
    dspm::Mat result(3, 4);
    result(0, 0) = q.data[0] * vector.data[0] + q.data[3] * vector.data[1] - q.data[2] * vector.data[2];
    result(0, 1) = q.data[1] * vector.data[0] + q.data[2] * vector.data[1] + q.data[3] * vector.data[2];
    result(0, 2) = -q.data[2] * vector.data[0] + q.data[1] * vector.data[1] - q.data[0] * vector.data[2];
    result(0, 3) = -q.data[3] * vector.data[0] + q.data[0] * vector.data[1] + q.data[1] * vector.data[2];
    result(1, 0) = -q.data[3] * vector.data[0] + q.data[0] * vector.data[1] + q.data[1] * vector.data[2];
    result(1, 1) = q.data[2] * vector.data[0] - q.data[1] * vector.data[1] + q.data[0] * vector.data[2];
    result(1, 2) = q.data[1] * vector.data[0] + q.data[2] * vector.data[1] + q.data[3] * vector.data[2];
    result(1, 3) = -q.data[0] * vector.data[0] - q.data[3] * vector.data[1] + q.data[2] * vector.data[2];
    result(2, 0) = q.data[2] * vector.data[0] - q.data[1] * vector.data[1] + q.data[0] * vector.data[2];
    result(2, 1) = q.data[3] * vector.data[0] - q.data[0] * vector.data[1] - q.data[1] * vector.data[2];
    result(2, 2) = q.data[0] * vector.data[0] + q.data[3] * vector.data[1] - q.data[2] * vector.data[2];
    result(2, 3) = q.data[1] * vector.data[0] + q.data[2] * vector.data[1] + q.data[3] * vector.data[2];
    result *= 2;
    return result;
}
References dspm::Mat::data.
Referenced by ekf_imu13states::UpdateRefMeasurement(), ekf_imu13states::UpdateRefMeasurement(), and ekf_imu13states::UpdateRefMeasurementMagn().
eul2rotm()
dspm::Mat ekf::eul2rotm (float xyz[3]) static
Convert Euler angels to rotation matrix.
Parameters
[in] xyz Euler angels
Returns
rotation matrix 3x3
Definition at line 251 of file ekf.cpp.
{
    dspm::Mat result(3, 3);
    float Cx = std::cos(xyz[0]);
    float Sx = std::sin(xyz[0]);
    float Cy = std::cos(xyz[1]);
    float Sy = std::sin(xyz[1]);
    float Cz = std::cos(xyz[2]);
    float Sz = std::sin(xyz[2]);
    result(0, 0) = Cy * Cz;
    result(0, 1) = -Cy * Sz;
    result(0, 2) = Sy;
    result(1, 0) = Cz * Sx * Sy + Cx * Sz;
    result(1, 1) = Cx * Cz - Sx * Sy * Sz;
    result(1, 2) = -Cy * Sx;
    result(2, 0) = -Cx * Cz * Sy + Sx * Sz;
    result(2, 1) = Cz * Sx + Cx * Sy * Sz;
    result(2, 2) = Cx * Cy;
    return result;
}
Referenced by draw_3d_image(), draw_3d_image(), draw_3d_image(), draw_3d_image(), ekf_imu13states::TestFull(), and update_rotation_matrix().
Init()
virtual void ekf::Init () pure virtual
Initialization of EKF. The method should be called befare the first use of the filter.
Implemented in ekf_imu13states.
LinearizeFG()
virtual void ekf::LinearizeFG (dspm::Mat & x, float * u) pure virtual
Calculation of system state matrices F and G
Parameters
[in] x state vector
[in] u control measurement
Implemented in ekf_imu13states.
References x.
Referenced by Process().
Process()
void ekf::Process (float * u, float dt) virtual
Main processing method of the EKF.
Parameters
[in] u - input measurements
[in] dt - time difference from the last call in seconds
Definition at line 53 of file ekf.cpp.
{
    this->LinearizeFG(this->X, (float *)u);
    this->RungeKutta(this->X, u, dt);
    this->CovariancePrediction(dt);
}
References CovariancePrediction(), LinearizeFG(), RungeKutta(), and X.
Referenced by ekf_imu13states::TestFull().
qProduct()
dspm::Mat ekf::qProduct (float * q) static
Make right quaternion-product matrices.
Parameters
[in] q source quaternion
Returns
right quaternion-product matrix 4x4
Definition at line 112 of file ekf.cpp.
{
    dspm::Mat result(4, 4);
    result.data[0] = q[0];
    result.data[1] = -q[1];
    result.data[2] = -q[2];
    result.data[3] = -q[3];
    result.data[4] = q[1];
    result.data[5] = q[0];
    result.data[6] = -q[3];
    result.data[7] = q[2];
    result.data[8] = q[2];
    result.data[9] = q[3];
    result.data[10] = q[0];
    result.data[11] = -q[1];
    result.data[12] = q[3];
    result.data[13] = -q[2];
    result.data[14] = q[1];
    result.data[15] = q[0];
    return result;
}
References dspm::Mat::data.
Referenced by ekf_imu13states::LinearizeFG().
quat2eul()
dspm::Mat ekf::quat2eul (const float q[4]) static
Convert quaternion to Euler angels.
Parameters
[in] q quaternion
Returns
Euler angels 3x1
Definition at line 230 of file ekf.cpp.
{
    dspm::Mat result(3, 1);
    float R13, R11, R12, R23, R33;
    float q0s = q[0] * q[0];
    float q1s = q[1] * q[1];
    float q2s = q[2] * q[2];
    float q3s = q[3] * q[3];
    R13 = 2.0f * (q[1] * q[3] + q[0] * q[2]);
    R11 = q0s + q1s - q2s - q3s;
    R12 = -2.0f * (q[1] * q[2] - q[0] * q[3]);
    R23 = -2.0f * (q[2] * q[3] - q[0] * q[1]);
    R33 = q0s - q1s - q2s + q3s;
    result.data[1] = (asinf(R13));
    result.data[2] = (atan2f(R12, R11));
    result.data[0] = (atan2f(R23, R33));
    return result;
}
References dspm::Mat::data.
quat2rotm()
dspm::Mat ekf::quat2rotm (float q[4]) static
Convert quaternion to rotation matrix.
Parameters
[in] q quaternion
Returns
rotation matrix 3x3
Definition at line 209 of file ekf.cpp.
{
    float q0 = q[0];
    float q1 = q[1];
    float q2 = q[2];
    float q3 = q[3];
    dspm::Mat Rm(3, 3);
    Rm(0, 0) = q0 * q0 + q1 * q1 - q2 * q2 - q3 * q3;
    Rm(1, 0) = 2.0f * (q1 * q2 + q0 * q3);
    Rm(2, 0) = 2.0f * (q1 * q3 - q0 * q2);
    Rm(0, 1) = 2.0f * (q1 * q2 - q0 * q3);
    Rm(1, 1) = (q0 * q0 - q1 * q1 + q2 * q2 - q3 * q3);
    Rm(2, 1) = 2.0f * (q2 * q3 + q0 * q1);
    Rm(0, 2) = 2.0f * (q1 * q3 + q0 * q2);
    Rm(1, 2) = 2.0f * (q2 * q3 - q0 * q1);
    Rm(2, 2) = (q0 * q0 - q1 * q1 - q2 * q2 + q3 * q3);
    return Rm;
}
Referenced by draw_3d_image(), draw_3d_image(), draw_3d_image(), draw_3d_image(), draw_3d_image_task(), draw_3d_image_task(), ekf_imu13states::LinearizeFG(), ekf_imu13states::UpdateRefMeasurement(), ekf_imu13states::UpdateRefMeasurement(), and ekf_imu13states::UpdateRefMeasurementMagn().
rotm2eul()
dspm::Mat ekf::rotm2eul (dspm::Mat & rotm) static
Convert rotation matrix to Euler angels.
Parameters
[in] rotm rotation matrix
Returns
Euler angels 3x1
Definition at line 279 of file ekf.cpp.
{
    dspm::Mat result(3, 1);
    float x, y, z;
//    float cy = sqrtf(rotm(2, 2) * rotm(2, 2) + rotm(2, 0) * rotm(2, 0));
    float cy = sqrtf(rotm(2, 2) * rotm(2, 2) + rotm(1, 2) * rotm(1, 2));
    if (cy > 16 * FLT_EPSILON) {
        x = -atan2f(rotm(1, 2), rotm(2, 2));
        y = -atan2f(-rotm(0, 2), (float)cy);
        z = -atan2f(rotm(0, 1), rotm(0, 0));
    } else {
        z = -atan2f(-rotm(1, 0), rotm(1, 1));
        y = -atan2f(-rotm(0, 2), (float)cy);
        x = 0;
    }
    result(0, 0) = x;
    result(1, 0) = y;
    result(2, 0) = z;
    return result;
}
References FLT_EPSILON, x, and y.
Referenced by draw_3d_image(), draw_3d_image(), draw_3d_image(), draw_3d_image(), draw_3d_image_task(), and draw_3d_image_task().
rotm2quat()
dspm::Mat ekf::rotm2quat (dspm::Mat & R) static
Convert rotation matrix to quaternion.
Parameters
[in] R rotation matrix
Returns
quaternion 4x1
Definition at line 305 of file ekf.cpp.
{
    float r11 = m(0, 0);
    float r12 = m(0, 1);
    float r13 = m(0, 2);
    float r21 = m(1, 0);
    float r22 = m(1, 1);
    float r23 = m(1, 2);
    float r31 = m(2, 0);
    float r32 = m(2, 1);
    float r33 = m(2, 2);
    float q0 = (r11 + r22 + r33 + 1.0f) / 4.0f;
    float q1 = (r11 - r22 - r33 + 1.0f) / 4.0f;
    float q2 = (-r11 + r22 - r33 + 1.0f) / 4.0f;
    float q3 = (-r11 - r22 + r33 + 1.0f) / 4.0f;
    if (q0 < 0.0f) {
        q0 = 0.0f;
    }
    if (q1 < 0.0f) {
        q1 = 0.0f;
    }
    if (q2 < 0.0f) {
        q2 = 0.0f;
    }
    if (q3 < 0.0f) {
        q3 = 0.0f;
    }
    q0 = sqrt(q0);
    q1 = sqrt(q1);
    q2 = sqrt(q2);
    q3 = sqrt(q3);
    if (q0 >= q1 && q0 >= q2 && q0 >= q3) {
        q0 *= +1.0f;
        q1 *= SIGN(r32 - r23);
        q2 *= SIGN(r13 - r31);
        q3 *= SIGN(r21 - r12);
    } else if (q1 >= q0 && q1 >= q2 && q1 >= q3) {
        q0 *= SIGN(r32 - r23);
        q1 *= +1.0f;
        q2 *= SIGN(r21 + r12);
        q3 *= SIGN(r13 + r31);
    } else if (q2 >= q0 && q2 >= q1 && q2 >= q3) {
        q0 *= SIGN(r13 - r31);
        q1 *= SIGN(r21 + r12);
        q2 *= +1.0f;
        q3 *= SIGN(r32 + r23);
    } else if (q3 >= q0 && q3 >= q1 && q3 >= q2) {
        q0 *= SIGN(r21 - r12);
        q1 *= SIGN(r31 + r13);
        q2 *= SIGN(r32 + r23);
        q3 *= +1.0f;
    }
    dspm::Mat res(4, 1);
    res(0, 0) = q0;
    res(1, 0) = q1;
    res(2, 0) = q2;
    res(3, 0) = q3;
    res /= res.norm();
    return res;
}
References m, dspm::Mat::norm(), and SIGN().
Referenced by ekf_imu13states::TestFull().
RungeKutta()
void ekf::RungeKutta (dspm::Mat & x, float * u, float dt)
Runge-Kutta state update method. The method calculates derivatives of input vector x and control measurements u
Parameters
[in] x state vector
[in] u control measurement
[in] dt time interval from last update in seconds
Definition at line 60 of file ekf.cpp.
{
    float dt2 = dt / 2.0f;
    dspm::Mat Xlast = x;          // make a working copy
    dspm::Mat K1 = StateXdot(x, U); // k1 = f(x, u)
    x = Xlast + (K1 * dt2);
    dspm::Mat K2 = StateXdot(x, U); // k2 = f(x + 0.5*dT*k1, u)
    x = Xlast + K2 * dt2;
    dspm::Mat K3 = StateXdot(x, U); // k3 = f(x + 0.5*dT*k2, u)
    x = Xlast + K3 * dt;
    dspm::Mat K4 = StateXdot(x, U); // k4 = f(x + dT * k3, u)
    // Xnew = X + dT * (k1 + 2 * k2 + 2 * k3 + k4) / 6
    x = Xlast + (K1 + 2.0f * K2 + 2.0f * K3 + K4) * (dt / 6.0f);
}
References StateXdot(), and x.
Referenced by Process().
SkewSym4x4()
dspm::Mat ekf::SkewSym4x4 (float * w) static
Make skew-symmetric matrix of vector.
Parameters
[in] w source vector
Returns
skew-symmetric matrix 4x4
Definition at line 81 of file ekf.cpp.
{
    //={    0,  -w[0],  -w[1],  -w[2],
    //   w[0],      0,   w[2],  -w[1],
    //   w[1],  -w[2],      0,   w[0],
    //   w[2],   w[1],  -w[0],     0 };
    dspm::Mat result(4, 4);
    result.data[0] = 0;
    result.data[1] = -w[0];
    result.data[2] = -w[1];
    result.data[3] = -w[2];
    result.data[4] = w[0];
    result.data[5] = 0;
    result.data[6] = w[2];
    result.data[7] = -w[1];
    result.data[8] = w[1];
    result.data[9] = -w[2];
    result.data[10] = 0;
    result.data[11] = w[0];
    result.data[12] = w[2];
    result.data[13] = w[1];
    result.data[14] = -w[0];
    result.data[15] = 0;
    return result;
}
References dspm::Mat::data.
Referenced by ekf_imu13states::LinearizeFG(), and ekf_imu13states::StateXdot().
StateXdot()
dspm::Mat ekf::StateXdot (dspm::Mat & x, float * u) virtual
Derivative of state vector X The default calculation: xDot = F*x + G*u It's possible to implement optimized version
Parameters
[in] x state vector
[in] u control measurement
Returns
xDot - derivative of input vector x and u
Reimplemented in ekf_imu13states.
Definition at line 411 of file ekf.cpp.
{
    dspm::Mat U(u, this->G.cols, 1);
    dspm::Mat Xdot = (this->F * x + this->G * U);
    return Xdot;
}
References F, G, and x.
Referenced by RungeKutta().
Update()
void ekf::Update (dspm::Mat & H, float * measured, float * expected, float * R) virtual
Update of current state by measured values. Optimized method for non correlated values Calculate Kalman gain and update matrix P and vector X.
Parameters
[in] H derivative matrix
[in] measured array of measured values
[in] expected array of expected values
[in] R measurement noise covariance values
Definition at line 149 of file ekf.cpp.
{
    float HPHR, Error;
    dspm::Mat Y(measured, H.rows, 1);
    dspm::Mat Z(expected, H.rows, 1);
    for (int m = 0; m < H.rows; m++) {
        for (int j = 0; j < this->NUMX; j++) {
            // Find Hp = H*P
            HP[j] = 0;
        }
        for (int k = 0; k < this->NUMX; k++) {
            for (int j = 0; j < this->NUMX; j++) {
                // Find Hp = H*P
                HP[j] += H(m, k) * P(k, j);
            }
        }
        HPHR = R[m]; // Find  HPHR = H*P*H' + R
        for (int k = 0; k < this->NUMX; k++) {
            HPHR += HP[k] * H(m, k);
        }
        float invHPHR = 1.0f / HPHR;
        for (int k = 0; k < this->NUMX; k++) {
            Km[k] = HP[k] * invHPHR; // find K = HP/HPHR
        }
        for (int i = 0; i < this->NUMX; i++) {
            // Find P(m)= P(m-1) + K*HP
            for (int j = i; j < NUMX; j++) {
                P(i, j) = P(j, i) = P(i, j) - Km[i] * HP[j];
            }
        }
        Error = Y(m, 0) - Z(m, 0);
        for (int i = 0; i < this->NUMX; i++) {
            // Find X(m)= X(m-1) + K*Error
            X(i, 0) = X(i, 0) + Km[i] * Error;
        }
    }
}
References HP, k, Km, m, NUMX, P, dspm::Mat::rows, and X.
Referenced by ekf_imu13states::UpdateRefMeasurement(), ekf_imu13states::UpdateRefMeasurement(), and ekf_imu13states::UpdateRefMeasurementMagn().
UpdateRef()
void ekf::UpdateRef (dspm::Mat & H, float * measured, float * expected, float * R) virtual
Update of current state by measured values. This method just as a reference for research purpose. Not used in real calculations.
Parameters
[in] H derivative matrix
[in] measured array of measured values
[in] expected array of expected values
[in] R measurement noise covariance values
Definition at line 189 of file ekf.cpp.
{
    dspm::Mat h_t = H.t();
    dspm::Mat S = H * P * h_t; // +diag(R);
    for (size_t i = 0; i < H.rows; i++) {
        S(i, i) += R[i];
    }
    dspm::Mat S_ = S.pinv(); // 1 / S
    dspm::Mat K = (P * h_t) * S_;
    this->P = (dspm::Mat::eye(this->NUMX) - K * H) * P;
    dspm::Mat Y(measured, H.rows, 1);
    dspm::Mat Z(expected, H.rows, 1);
    dspm::Mat Err = Y - Z;
    this->X += (K * Err);
}
References dspm::Mat::eye(), K, NUMX, P, dspm::Mat::pinv(), dspm::Mat::rows, dspm::Mat::t(), and X.
Field Documentation
F
dspm::Mat& ekf::F
Linearized system matrices F, where xDot[n] = F*x[n] + G*u + W
Definition at line 78 of file ekf.h.
Referenced by CovariancePrediction(), ekf(), ekf_imu13states::LinearizeFG(), StateXdot(), and ~ekf().
G
dspm::Mat& ekf::G
Linearized system matrices G, where xDot[n] = F*x[n] + G*u + W
Definition at line 82 of file ekf.h.
Referenced by CovariancePrediction(), ekf(), ekf_imu13states::LinearizeFG(), StateXdot(), and ~ekf().
HP
float* ekf::HP
Matrix for intermidieve calculations
Definition at line 157 of file ekf.h.
Referenced by ekf(), Update(), and ~ekf().
Km
float* ekf::Km
Matrix for intermidieve calculations
Definition at line 161 of file ekf.h.
Referenced by ekf(), Update(), and ~ekf().
NUMW
int ekf::NUMW
xDot[n] = F*x[n] + G*u + W The size of G matrix
Definition at line 68 of file ekf.h.
Referenced by ekf().
NUMX
int ekf::NUMX
xDot[n] = F*x[n] + G*u + W Number of states, X is the state vector (size of F matrix)
Definition at line 63 of file ekf.h.
Referenced by CovariancePrediction(), ekf(), ekf_imu13states::StateXdot(), Update(), UpdateRef(), ekf_imu13states::UpdateRefMeasurement(), ekf_imu13states::UpdateRefMeasurement(), and ekf_imu13states::UpdateRefMeasurementMagn().
P
dspm::Mat& ekf::P
Covariance matrix and state vector
Definition at line 87 of file ekf.h.
Referenced by CovariancePrediction(), ekf(), Update(), UpdateRef(), and ~ekf().
Q
dspm::Mat& ekf::Q
Input noise and measurement noise variances
Definition at line 92 of file ekf.h.
Referenced by CovariancePrediction(), ekf(), ekf_imu13states::Init(), and ~ekf().
X
dspm::Mat& ekf::X
System state vector
Definition at line 73 of file ekf.h.
Referenced by ekf(), ekf_imu13states::Init(), Process(), ekf_imu13states::TestFull(), Update(), UpdateRef(), ekf_imu13states::UpdateRefMeasurement(), ekf_imu13states::UpdateRefMeasurement(), ekf_imu13states::UpdateRefMeasurementMagn(), and ~ekf().
The documentation for this class was generated from the following files:
ekf.h
ekf.cpp