ESP-IDF Firmware: main.c File Reference
main.c File Reference
Functions
void test_mmult ()
int main (void)
Function Documentation
main()
int main (void)
Definition at line 4 of file components/espressif__esp-dsp/modules/matrix/mul/test_sim/main.c.
{
    printf("main starts!\n");
//    xt_iss_profile_enable();
    test_mmult();
//    xt_iss_profile_disable();
    printf("Test done\n");
}
References test_mmult().
test_mmult()
void test_mmult ()
Definition at line 25 of file test_mmult.c.
{
    float *A_ptr = (float *)A;
    float *B_ptr = (float *)B;
    float *C_ptr = (float *)C;
    float *Cc_ptr = (float *)C_compare;
    for (int i = 0 ; i < m * n; i++) {
        A_ptr[i] = i;
        B_ptr[i] = i;
    }
    for (int i = 0 ; i < m ; i++) {
        for (int j = 0 ; j < k ; j++) {
            C_compare[i][j] = 0;
            for (int s = 0 ; s < n ; s++) {
                C_compare[i][j] += A[i][s] * B[s][j];
            }
            C[i][j] = -1;
        }
    }
    xt_iss_profile_enable();
    dspm_mult_f32_ae32(A_ptr, B_ptr, Cc_ptr, m, n, k);
    dspm_mult_f32_aes3(A_ptr, B_ptr, C_ptr, m, n, k);
    xt_iss_profile_disable();
    for (int i = 0 ; i < m ; i++) {
        for (int j = 0 ; j < k ; j++) {
            printf("[%i][%i] calc=%f, expected =%f\n", i, j, C[i][j], C_compare[i][j]);
        }
    }
    // Compare and check results
    for (int i = 0 ; i < m * k ; i++) {
        if (Cc_ptr[i] != C_ptr[i]) {
            printf("Error - C_ptr= %f, Cc_ptr= %f \n", C_ptr[i], Cc_ptr[i]);
            return;
        }
    }
    printf("Test Pass!\n");
}
References A, B, C, C_compare, dspm_mult_f32_ae32(), dspm_mult_f32_aes3(), k, m, n, xt_iss_profile_disable(), and xt_iss_profile_enable().
Referenced by main().