ESP-IDF Firmware: main.c File Reference
main.c File Reference
Functions
void test_iir_biquad ()
int main (void)
Function Documentation
main()
int main (void)
Definition at line 4 of file components/espressif__esp-dsp/modules/iir/test_sim/main.c.
{
    printf("main starts!\n");
//    xt_iss_profile_enable();
    test_iir_biquad();
//    xt_iss_profile_disable();
    printf("Test done\n");
}
References test_iir_biquad().
test_iir_biquad()
void test_iir_biquad ()
Definition at line 22 of file test_iir_biquad.c.
{
    float coeffs_lpf[5] = {0.073802,  0.147603,  0.073802,  -1.250516,  0.545723};
    float w_lpf[5] = {0, 0};
    float w_lpf_ref[5] = {0, 0};
    esp_err_t ret = ESP_OK;
    for (size_t i = 0; i < N; i++) {
        d[i] = 0;
    }
    d[0] = 1;
    xt_iss_profile_enable();
    ret = dsps_biquad_f32_ansi(d, y_ref, N, coeffs_lpf, w_lpf_ref);
    xt_iss_profile_disable();
    if (ret  != ESP_OK) {
        printf("dsps_biquad_f32 error = %i\n", ret);
        return;
    }
    xt_iss_profile_enable();
    ret = dsps_biquad_f32_aes3(d, y, N, coeffs_lpf, w_lpf);
    xt_iss_profile_disable();
    if (ret  != ESP_OK) {
        printf("dsps_biquad_f32 error = %i\n", ret);
        return;
    }
    for (size_t i = 0; i < N; i++) {
        if (((y[i] - y_ref[i]) > 0.0000001) || (y[i] - y_ref[i]) < -0.0000001) {
            printf("ERROR result[%i]: %f, expect = %f, diff=%f\n", i, y[i], y_ref[i], y[i] - y_ref[i]);
            return;
        }
    }
    printf("Test Correct!\n");
}
References d, dsps_biquad_f32_aes3(), dsps_biquad_f32_ansi(), ESP_OK, N, xt_iss_profile_disable(), xt_iss_profile_enable(), y, and y_ref.
Referenced by main().