ESP-IDF Firmware: main.c File Reference
main.c File Reference
Functions
void test_fir ()
int main (void)
Function Documentation
main()
int main (void)
Definition at line 4 of file components/espressif__esp-dsp/modules/fir/test_sim/main.c.
{
    printf("main starts!\n");
//    xt_iss_profile_enable();
    test_fir();
//    xt_iss_profile_disable();
    printf("Test done\n");
}
References test_fir().
test_fir()
void test_fir ()
Definition at line 19 of file test_fir.c.
{
    int len = sizeof(x) / sizeof(float);
    int fir_len = sizeof(coeffs) / sizeof(float);
    fir_f32_t fir1;
    fir_f32_t fir2;
    for (int i = 0 ; i < fir_len ; i++) {
        coeffs[i] = i;
    }
    for (int i = 0 ; i < len ; i++) {
        x[i] = 0;
    }
    x[0] = 1;
    for (int i = 0 ; i < fir_len ; i++) {
        coeffs[i] = i;
    }
    for (int i = 0 ; i < len ; i++) {
        x[i] = i;
    }
    x[0] = 1;
    dsps_fir_init_f32(&fir1, coeffs, delay, fir_len / 4);
    dsps_fir_init_f32(&fir2, coeffs, delay_compare, fir_len);
    xt_iss_profile_enable();
    dsps_fir_f32_aes3(&fir1, x, y, len);
    dsps_fir_f32_ansi(&fir2, x, y_compare, len);
    xt_iss_profile_disable();
    printf("Test Pass!\n");
}
References coeffs, delay, delay_compare, dsps_fir_f32_aes3(), dsps_fir_f32_ansi(), dsps_fir_init_f32(), x, xt_iss_profile_disable(), xt_iss_profile_enable(), y, and y_compare.
Referenced by main().