ESP-IDF Firmware: dsps_snr.h File Reference
dsps_snr.h File Reference
#include "dsp_err.h"
Functions
float dsps_snr_f32 (const float *input, int32_t len, uint8_t use_dc)
SNR.
float dsps_snr_fc32 (const float *input, int32_t len)
Function Documentation
dsps_snr_f32()
float dsps_snr_f32 (const float * input, int32_t len, uint8_t use_dc)
SNR.
The function calculates signal to noise ration in case if signal is sine tone. The function makes FFT of the input, then search a spectrum maximum, and then calculated SNR as sum of all harmonics to the maximum value. This function have to be used for debug and unit tests only. It's not optimized for real-time processing. The implementation use ANSI C and could be compiled and run on any platform
Parameters
input input array.
len length of the input signal
use_dc this parameter define will be DC value used for calculation or not. 0 - SNR will not include DC power 1 - SNR will include DC power
Returns
SNR in dB
Definition at line 24 of file dsps_snr_f32.cpp.
{
    if (!dsp_is_power_of_two(len)) {
        return 0;
    }
    float *temp_array = new float[len * 2];
    for (int i = 0 ; i < len ; i++) {
        float wind = 0.5 * (1 - cosf(i * 2 * M_PI / (float)len));
        temp_array[i * 2 + 0] = input[i] * wind;
        temp_array[i * 2 + 1] = 0;
    }
    dsps_fft2r_init_fc32(NULL, CONFIG_DSP_MAX_FFT_SIZE);
    dsps_fft2r_fc32_ansi(temp_array, len);
    dsps_bit_rev_fc32_ansi(temp_array, len);
    float min = std::numeric_limits<float>::max();
    float max = std::numeric_limits<float>::min();
    int max_pos = 0;
    for (int i = 0 ; i < len / 2 ; i++) {
        temp_array[i] = temp_array[i * 2 + 0] * temp_array[i * 2 + 0] + temp_array[i * 2 + 1] * temp_array[i * 2 + 1];
        if (temp_array[i] < min) {
            min = temp_array[i];
        }
        if (temp_array[i] > max) {
            max = temp_array[i];
            max_pos = i;
        }
        ESP_LOGD(TAG, "FFT Data[%i] =%8.4f dB", i, temp_array[i]);
    }
    int start_pos = 0;
    int wind_width = 7;
    if (use_dc == 0) {
        start_pos = wind_width;
    }
    float noise_power = 0;
    for (int i = start_pos ; i < len / 2 ; i++) {
        if ((i < (max_pos - wind_width)) || (i > (max_pos + wind_width))) {
            noise_power += temp_array[i];
            ESP_LOGD(TAG, "FFT Data[%i] =%8.4f dB, maX=%f, max_pos=%i, noise_power=%f", i, temp_array[i], max, max_pos, noise_power);
        }
    }
    delete[] temp_array;
    noise_power += std::numeric_limits<float>::min();
    if (noise_power < max * 0.00000000001) {
        return 192;
    }
    float snr = max / noise_power;
    float result = 10 * log10(max / noise_power) - 2; // 2 - window correction
    ESP_LOGI(TAG, "SNR = %f, result=%f dB", snr, result);
    return result;
}
References CONFIG_DSP_MAX_FFT_SIZE, dsp_is_power_of_two(), dsps_bit_rev_fc32_ansi(), dsps_fft2r_fc32_ansi, dsps_fft2r_init_fc32(), ESP_LOGD, M_PI, and TAG.
dsps_snr_fc32()
float dsps_snr_fc32 (const float * input, int32_t len)