ESP-IDF Firmware: dsps_mulc.h File Reference
dsps_mulc.h File Reference
#include "dsp_err.h"
#include "dsps_mulc_platform.h"
#define dsps_mulc_f32 dsps_mulc_f32_ansi
#define dsps_mulc_s16 dsps_mulc_s16_ansi
esp_err_t dsps_mulc_f32_ansi (const float *input, float *output, int len, float C, int step_in, int step_out)
multiply constant
esp_err_t dsps_mulc_f32_ae32 (const float *input, float *output, int len, float C, int step_in, int step_out)
esp_err_t dsps_mulc_s16_ae32 (const int16_t *input, int16_t *output, int len, int16_t C, int step_in, int step_out)
esp_err_t dsps_mulc_s16_ansi (const int16_t *input, int16_t *output, int len, int16_t C, int step_in, int step_out)
Macro Definition Documentation
dsps_mulc_f32
#define dsps_mulc_f32 dsps_mulc_f32_ansi
Definition at line 69 of file dsps_mulc.h.
dsps_mulc_s16
#define dsps_mulc_s16 dsps_mulc_s16_ansi
Definition at line 70 of file dsps_mulc.h.
Function Documentation
dsps_mulc_f32_ae32()
esp_err_t dsps_mulc_f32_ae32 (const float * input, float * output, int len, float C, int step_in, int step_out)
References C.
dsps_mulc_f32_ansi()
esp_err_t dsps_mulc_f32_ansi (const float * input, float * output, int len, float C, int step_in, int step_out)
multiply constant
The function multiplies input array to the constant value x[i*step_out] = y[i*step_in]*C; i=[0..len) The implementation use ANSI C and could be compiled and run on any platform
Parameters
[in] input input array
output output array
len amount of operations for arrays
C constant value
step_in step over input array (by default should be 1)
step_out step over output array (by default should be 1)
Returns
ESP_OK on success
One of the error codes from DSP library
Definition at line 17 of file dsps_mulc_f32_ansi.c.
{
    if (NULL == input) {
        return ESP_ERR_DSP_PARAM_OUTOFRANGE;
    }
    if (NULL == output) {
        return ESP_ERR_DSP_PARAM_OUTOFRANGE;
    }
    for (int i = 0 ; i < len ; i++) {
        output[i * step_out] = input[i * step_in] * C;
    }
    return ESP_OK;
}
References C, ESP_ERR_DSP_PARAM_OUTOFRANGE, and ESP_OK.
Referenced by audio_read_task(), audio_read_task(), audio_read_task(), dspm::Mat::operator*=(), and dspm::Mat::operator/=().
dsps_mulc_s16_ae32()
esp_err_t dsps_mulc_s16_ae32 (const int16_t * input, int16_t * output, int len, int16_t C, int step_in, int step_out)
References C.
dsps_mulc_s16_ansi()
esp_err_t dsps_mulc_s16_ansi (const int16_t * input, int16_t * output, int len, int16_t C, int step_in, int step_out)
Definition at line 17 of file dsps_mulc_s16_ansi.c.
{
    if (NULL == input) {
        return ESP_ERR_DSP_PARAM_OUTOFRANGE;
    }
    if (NULL == output) {
        return ESP_ERR_DSP_PARAM_OUTOFRANGE;
    }
    for (int i = 0 ; i < len ; i++) {
        int32_t acc = (int32_t)input[i * step_in] * (int32_t)C;
        output[i * step_out] = (int16_t)(acc >> 15);
    }
    return ESP_OK;
}
References C, ESP_ERR_DSP_PARAM_OUTOFRANGE, and ESP_OK.