ESP-IDF Firmware: dsps_sfdr_f32.cpp File Reference
dsps_sfdr_f32.cpp File Reference
#include "dsps_sfdr.h"
#include "dsps_fft2r.h"
#include "dsp_common.h"
#include <math.h>
#include <limits>
#include "esp_log.h"
Functions
float dsps_sfdr_f32 (const float *input, int32_t len, int8_t use_dc)
SFDR.
Variables
static const char * TAG = "sfdr"
Function Documentation
dsps_sfdr_f32()
float dsps_sfdr_f32 (const float * input, int32_t len, int8_t use_dc)
SFDR.
The function calculates Spurious-Free Dynamic Range. The function makes FFT of the input, then search a spectrum maximum, and then compare maximum value with all others. Result calculated as minimum value. This function have to be used for debug and unit tests only. It's not optimized for real-time processing. The implementation use ANSI C and could be compiled and run on any platform
Parameters
[in] input input array.
len length of the input signal
use_dc this parameter define will be DC value used for calculation or not. 0 - SNR will not include DC power 1 - SNR will include DC power
Returns
SFDR in DB
Definition at line 24 of file dsps_sfdr_f32.cpp.
{
    if (!dsp_is_power_of_two(len)) {
        return 0;
    }
    float *temp_array = new float[len * 2];
    for (int i = 0 ; i < len ; i++) {
        float wind = 0.5 * (1 - cosf(i * 2 * M_PI / (float)len));
        temp_array[i * 2 + 0] = input[i] * wind;
        temp_array[i * 2 + 1] = 0;
    }
    dsps_fft2r_init_fc32(NULL, CONFIG_DSP_MAX_FFT_SIZE);
    dsps_fft2r_fc32_ansi(temp_array, len);
    dsps_bit_rev_fc32_ansi(temp_array, len);
    float min = std::numeric_limits<float>::max();
    float max = std::numeric_limits<float>::min();
    int max_pos = 0;
    for (int i = 0 ; i < len / 2 ; i++) {
        temp_array[i] = 10 * log10f(temp_array[i * 2 + 0] * temp_array[i * 2 + 0] + temp_array[i * 2 + 1] * temp_array[i * 2 + 1]);
        if (temp_array[i] < min) {
            min = temp_array[i];
        }
        if (temp_array[i] > max) {
            max = temp_array[i];
            max_pos = i;
        }
        ESP_LOGD(TAG, "FFT Data[%i] =%8.4f dB", i, temp_array[i]);
    }
    int start_pos = 0;
    int wind_width = 5;
    float min_diff = std::numeric_limits<float>::max();
    if (use_dc == 0) {
        start_pos = wind_width;
    }
    for (int i = start_pos ; i < len / 2 ; i++) {
        if ((i < (max_pos - wind_width)) || (i > (max_pos + wind_width))) {
            float diff = max - temp_array[i];
            if (diff < min_diff) {
                ESP_LOGD(TAG, "FFT Data[%i] =%8.4f dB, maX=%f, max_pos=%i", i, temp_array[i], max, max_pos);
                min_diff = diff;
            }
        }
    }
    delete[] temp_array;
    return min_diff;
}
References CONFIG_DSP_MAX_FFT_SIZE, dsp_is_power_of_two(), dsps_bit_rev_fc32_ansi(), dsps_fft2r_fc32_ansi, dsps_fft2r_init_fc32(), ESP_LOGD, M_PI, and TAG.
Variable Documentation
TAG
const char* TAG = "sfdr" static
Definition at line 22 of file dsps_sfdr_f32.cpp.