ESP-IDF Firmware: dsps_biquad_gen_f32.c File Reference
dsps_biquad_gen_f32.c File Reference
#include "dsps_biquad_gen.h"
#include <math.h>
#include "esp_log.h"
Functions
esp_err_t dsps_biquad_gen_lpf_f32 (float *coeffs, float f, float qFactor)
LPF IIR filter coefficients Coefficients for low pass 2nd order IIR filter (bi-quad) The implementation use ANSI C and could be compiled and run on any platform.
esp_err_t dsps_biquad_gen_hpf_f32 (float *coeffs, float f, float qFactor)
HPF IIR filter coefficients.
esp_err_t dsps_biquad_gen_bpf_f32 (float *coeffs, float f, float qFactor)
BPF IIR filter coefficients.
esp_err_t dsps_biquad_gen_bpf0db_f32 (float *coeffs, float f, float qFactor)
0 dB BPF IIR filter coefficients
esp_err_t dsps_biquad_gen_notch_f32 (float *coeffs, float f, float gain, float qFactor)
Notch IIR filter coefficients.
esp_err_t dsps_biquad_gen_allpass360_f32 (float *coeffs, float f, float qFactor)
Allpass 360 degree IIR filter coefficients.
esp_err_t dsps_biquad_gen_allpass180_f32 (float *coeffs, float f, float qFactor)
Allpass 180 degree IIR filter coefficients.
esp_err_t dsps_biquad_gen_peakingEQ_f32 (float *coeffs, float f, float qFactor)
peak IIR filter coefficients
esp_err_t dsps_biquad_gen_lowShelf_f32 (float *coeffs, float f, float gain, float qFactor)
low shelf IIR filter coefficients
esp_err_t dsps_biquad_gen_highShelf_f32 (float *coeffs, float f, float gain, float qFactor)
high shelf IIR filter coefficients
Function Documentation
dsps_biquad_gen_allpass180_f32()
esp_err_t dsps_biquad_gen_allpass180_f32 (float * coeffs, float f, float qFactor)
Allpass 180 degree IIR filter coefficients.
Coefficients for all pass 2nd order IIR filter (bi-quad) with 180 degree phase shift The implementation use ANSI C and could be compiled and run on any platform
Parameters
coeffs result coefficients. b0,b1,b2,a1,a2, a0 are not placed to the array and expected by IIR as 1
f filter notch frequency in range of 0..0.5 (normalized to sample frequency)
qFactor Q factor of filter
Returns
ESP_OK on success
One of the error codes from DSP library
Definition at line 182 of file dsps_biquad_gen_f32.c.
{
    if (qFactor <= 0.0001) {
        qFactor = 0.0001;
    }
    float Fs = 1;
    float w0 = 2 * M_PI * f / Fs;
    float c = cosf(w0);
    float s = sinf(w0);
    float alpha = s / (2 * qFactor);
    float b0 = 1 - alpha;
    float b1 = -2 * c;
    float b2 = 1 + alpha;
    float a0 = 1 + alpha;
    float a1 = -2 * c;
    float a2 = 1 - alpha;
    coeffs[0] = b0 / a0;
    coeffs[1] = b1 / a0;
    coeffs[2] = b2 / a0;
    coeffs[3] = a1 / a0;
    coeffs[4] = a2 / a0;
    return ESP_OK;
}
References coeffs, ESP_OK, and M_PI.
dsps_biquad_gen_allpass360_f32()
esp_err_t dsps_biquad_gen_allpass360_f32 (float * coeffs, float f, float qFactor)
Allpass 360 degree IIR filter coefficients.
Coefficients for all pass 2nd order IIR filter (bi-quad) with 360 degree phase shift The implementation use ANSI C and could be compiled and run on any platform
Parameters
coeffs result coefficients. b0,b1,b2,a1,a2, a0 are not placed to the array and expected by IIR as 1
f filter notch frequency in range of 0..0.5 (normalized to sample frequency)
qFactor Q factor of filter
Returns
ESP_OK on success
One of the error codes from DSP library
Definition at line 155 of file dsps_biquad_gen_f32.c.
{
    if (qFactor <= 0.0001) {
        qFactor = 0.0001;
    }
    float Fs = 1;
    float w0 = 2 * M_PI * f / Fs;
    float c = cosf(w0);
    float s = sinf(w0);
    float alpha = s / (2 * qFactor);
    float b0 = 1 - alpha;
    float b1 = -2 * c;
    float b2 = 1 + alpha;
    float a0 = 1 + alpha;
    float a1 = -2 * c;
    float a2 = 1 - alpha;
    coeffs[0] = b0 / a0;
    coeffs[1] = b1 / a0;
    coeffs[2] = b2 / a0;
    coeffs[3] = a1 / a0;
    coeffs[4] = a2 / a0;
    return ESP_OK;
}
References coeffs, ESP_OK, and M_PI.
dsps_biquad_gen_bpf0db_f32()
esp_err_t dsps_biquad_gen_bpf0db_f32 (float * coeffs, float f, float qFactor)
0 dB BPF IIR filter coefficients
Coefficients for band pass 2nd order IIR filter (bi-quad) with 0 dB gain in passband The implementation use ANSI C and could be compiled and run on any platform
Parameters
coeffs result coefficients. b0,b1,b2,a1,a2, a0 are not placed to the array and expected by IIR as 1
f filter center frequency in range of 0..0.5 (normalized to sample frequency)
qFactor Q factor of filter
Returns
ESP_OK on success
One of the error codes from DSP library
Definition at line 100 of file dsps_biquad_gen_f32.c.
{
    if (qFactor <= 0.0001) {
        qFactor = 0.0001;
    }
    float Fs = 1;
    float w0 = 2 * M_PI * f / Fs;
    float c = cosf(w0);
    float s = sinf(w0);
    float alpha = s / (2 * qFactor);
    float b0 = alpha;
    float b1 = 0;
    float b2 = -alpha;
    float a0 = 1 + alpha;
    float a1 = -2 * c;
    float a2 = 1 - alpha;
    coeffs[0] = b0 / a0;
    coeffs[1] = b1 / a0;
    coeffs[2] = b2 / a0;
    coeffs[3] = a1 / a0;
    coeffs[4] = a2 / a0;
    return ESP_OK;
}
References coeffs, ESP_OK, and M_PI.
dsps_biquad_gen_bpf_f32()
esp_err_t dsps_biquad_gen_bpf_f32 (float * coeffs, float f, float qFactor)
BPF IIR filter coefficients.
Coefficients for band pass 2nd order IIR filter (bi-quad) The implementation use ANSI C and could be compiled and run on any platform
Parameters
coeffs result coefficients. b0,b1,b2,a1,a2, a0 are not placed to the array and expected by IIR as 1
f filter center frequency in range of 0..0.5 (normalized to sample frequency)
qFactor Q factor of filter
Returns
ESP_OK on success
One of the error codes from DSP library
Definition at line 73 of file dsps_biquad_gen_f32.c.
{
    if (qFactor <= 0.0001) {
        qFactor = 0.0001;
    }
    float Fs = 1;
    float w0 = 2 * M_PI * f / Fs;
    float c = cosf(w0);
    float s = sinf(w0);
    float alpha = s / (2 * qFactor);
    float b0 = s / 2;
    float b1 = 0;
    float b2 = -b0;
    float a0 = 1 + alpha;
    float a1 = -2 * c;
    float a2 = 1 - alpha;
    coeffs[0] = b0 / a0;
    coeffs[1] = b1 / a0;
    coeffs[2] = b2 / a0;
    coeffs[3] = a1 / a0;
    coeffs[4] = a2 / a0;
    return ESP_OK;
}
References coeffs, ESP_OK, and M_PI.
dsps_biquad_gen_highShelf_f32()
esp_err_t dsps_biquad_gen_highShelf_f32 (float * coeffs, float f, float gain, float qFactor)
high shelf IIR filter coefficients
Coefficients for high pass Shelf 2nd order IIR filter (bi-quad) The implementation use ANSI C and could be compiled and run on any platform
Parameters
coeffs result coefficients. b0,b1,b2,a1,a2, a0 are not placed to the array and expected by IIR as 1
f filter notch frequency in range of 0..0.5 (normalized to sample frequency)
gain gain in stopband in dB
qFactor Q factor of filter
Returns
ESP_OK on success
One of the error codes from DSP library
Definition at line 264 of file dsps_biquad_gen_f32.c.
{
    if (qFactor <= 0.0001) {
        qFactor = 0.0001;
    }
    float Fs = 1;
    float A = sqrtf(pow(10, (double)gain / 20.0));
    float w0 = 2 * M_PI * f / Fs;
    float c = cosf(w0);
    float s = sinf(w0);
    float alpha = s / (2 * qFactor);
    float b0 = A * ((A + 1) + (A - 1) * c + 2 * sqrtf(A) * alpha);
    float b1 = -2 * A * ((A - 1) + (A + 1) * c);
    float b2 = A * ((A + 1) + (A - 1) * c - 2 * sqrtf(A) * alpha);
    float a0 = (A + 1) - (A - 1) * c + 2 * sqrtf(A) * alpha;
    float a1 = 2 * ((A - 1) - (A + 1) * c);
    float a2 = (A + 1) - (A - 1) * c - 2 * sqrtf(A) * alpha;
    coeffs[0] = b0 / a0;
    coeffs[1] = b1 / a0;
    coeffs[2] = b2 / a0;
    coeffs[3] = a1 / a0;
    coeffs[4] = a2 / a0;
    return ESP_OK;
}
References A, coeffs, ESP_OK, and M_PI.
Referenced by audio_process_task(), audio_process_task(), audio_process_task(), buttons_process_task(), buttons_process_task(), and buttons_process_task().
dsps_biquad_gen_hpf_f32()
esp_err_t dsps_biquad_gen_hpf_f32 (float * coeffs, float f, float qFactor)
HPF IIR filter coefficients.
Coefficients for high pass 2nd order IIR filter (bi-quad) The implementation use ANSI C and could be compiled and run on any platform
Parameters
coeffs result coefficients. b0,b1,b2,a1,a2, a0 are not placed to the array and expected by IIR as 1
f filter cut off frequency in range of 0..0.5 (normalized to sample frequency)
qFactor Q factor of filter
Returns
ESP_OK on success
One of the error codes from DSP library
Definition at line 46 of file dsps_biquad_gen_f32.c.
{
    if (qFactor <= 0.0001) {
        qFactor = 0.0001;
    }
    float Fs = 1;
    float w0 = 2 * M_PI * f / Fs;
    float c = cosf(w0);
    float s = sinf(w0);
    float alpha = s / (2 * qFactor);
    float b0 = (1 + c) / 2;
    float b1 = -(1 + c);
    float b2 = b0;
    float a0 = 1 + alpha;
    float a1 = -2 * c;
    float a2 = 1 - alpha;
    coeffs[0] = b0 / a0;
    coeffs[1] = b1 / a0;
    coeffs[2] = b2 / a0;
    coeffs[3] = a1 / a0;
    coeffs[4] = a2 / a0;
    return ESP_OK;
}
References coeffs, ESP_OK, and M_PI.
dsps_biquad_gen_lowShelf_f32()
esp_err_t dsps_biquad_gen_lowShelf_f32 (float * coeffs, float f, float gain, float qFactor)
low shelf IIR filter coefficients
Coefficients for low pass Shelf 2nd order IIR filter (bi-quad) The implementation use ANSI C and could be compiled and run on any platform
Parameters
coeffs result coefficients. b0,b1,b2,a1,a2, a0 are not placed to the array and expected by IIR as 1
f filter notch frequency in range of 0..0.5 (normalized to sample frequency)
gain gain in stopband in dB
qFactor Q factor of filter
Returns
ESP_OK on success
One of the error codes from DSP library
Definition at line 236 of file dsps_biquad_gen_f32.c.
{
    if (qFactor <= 0.0001) {
        qFactor = 0.0001;
    }
    float Fs = 1;
    float A = sqrtf(pow(10, (double)gain / 20.0));
    float w0 = 2 * M_PI * f / Fs;
    float c = cosf(w0);
    float s = sinf(w0);
    float alpha = s / (2 * qFactor);
    float b0 = A * ((A + 1) - (A - 1) * c + 2 * sqrtf(A) * alpha);
    float b1 = 2 * A * ((A - 1) - (A + 1) * c);
    float b2 = A * ((A + 1) - (A - 1) * c - 2 * sqrtf(A) * alpha);
    float a0 = (A + 1) + (A - 1) * c + 2 * sqrtf(A) * alpha;
    float a1 = -2 * ((A - 1) + (A + 1) * c);
    float a2 = (A + 1) + (A - 1) * c - 2 * sqrtf(A) * alpha;
    coeffs[0] = b0 / a0;
    coeffs[1] = b1 / a0;
    coeffs[2] = b2 / a0;
    coeffs[3] = a1 / a0;
    coeffs[4] = a2 / a0;
    return ESP_OK;
}
References A, coeffs, ESP_OK, and M_PI.
Referenced by audio_process_task(), audio_process_task(), audio_process_task(), buttons_process_task(), buttons_process_task(), and buttons_process_task().
dsps_biquad_gen_lpf_f32()
esp_err_t dsps_biquad_gen_lpf_f32 (float * coeffs, float f, float qFactor)
LPF IIR filter coefficients Coefficients for low pass 2nd order IIR filter (bi-quad) The implementation use ANSI C and could be compiled and run on any platform.
Parameters
coeffs result coefficients. b0,b1,b2,a1,a2, a0 are not placed to the array and expected by IIR as 1
f filter cut off frequency in range of 0..0.5 (normalized to sample frequency)
qFactor Q factor of filter
Returns
ESP_OK on success
One of the error codes from DSP library
Definition at line 19 of file dsps_biquad_gen_f32.c.
{
    if (qFactor <= 0.0001) {
        qFactor = 0.0001;
    }
    float Fs = 1;
    float w0 = 2 * M_PI * f / Fs;
    float c = cosf(w0);
    float s = sinf(w0);
    float alpha = s / (2 * qFactor);
    float b0 = (1 - c) / 2;
    float b1 = 1 - c;
    float b2 = b0;
    float a0 = 1 + alpha;
    float a1 = -2 * c;
    float a2 = 1 - alpha;
    coeffs[0] = b0 / a0;
    coeffs[1] = b1 / a0;
    coeffs[2] = b2 / a0;
    coeffs[3] = a1 / a0;
    coeffs[4] = a2 / a0;
    return ESP_OK;
}
References coeffs, ESP_OK, and M_PI.
dsps_biquad_gen_notch_f32()
esp_err_t dsps_biquad_gen_notch_f32 (float * coeffs, float f, float gain, float qFactor)
Notch IIR filter coefficients.
Coefficients for notch 2nd order IIR filter (bi-quad) The implementation use ANSI C and could be compiled and run on any platform
Parameters
coeffs result coefficients. b0,b1,b2,a1,a2, a0 are not placed to the array and expected by IIR as 1
f filter notch frequency in range of 0..0.5 (normalized to sample frequency)
gain gain in stopband in dB
qFactor Q factor of filter
Returns
ESP_OK on success
One of the error codes from DSP library
Definition at line 127 of file dsps_biquad_gen_f32.c.
{
    if (qFactor <= 0.0001) {
        qFactor = 0.0001;
    }
    float Fs = 1;
    float A = sqrtf(pow(10, (double)gain / 20.0));
    float w0 = 2 * M_PI * f / Fs;
    float c = cosf(w0);
    float s = sinf(w0);
    float alpha = s / (2 * qFactor);
    float b0 = 1 + alpha * A;
    float b1 = -2 * c;
    float b2 = 1 - alpha * A;
    float a0 = 1 + alpha;
    float a1 = -2 * c;
    float a2 = 1 - alpha;
    coeffs[0] = b0 / a0;
    coeffs[1] = b1 / a0;
    coeffs[2] = b2 / a0;
    coeffs[3] = a1 / a0;
    coeffs[4] = a2 / a0;
    return ESP_OK;
}
References A, coeffs, ESP_OK, and M_PI.
dsps_biquad_gen_peakingEQ_f32()
esp_err_t dsps_biquad_gen_peakingEQ_f32 (float * coeffs, float f, float qFactor)
peak IIR filter coefficients
Coefficients for peak 2nd order IIR filter (bi-quad) The implementation use ANSI C and could be compiled and run on any platform
Parameters
coeffs result coefficients. b0,b1,b2,a1,a2, a0 are not placed to the array and expected by IIR as 1
f filter notch frequency in range of 0..0.5 (normalized to sample frequency)
qFactor Q factor of filter
Returns
ESP_OK on success
One of the error codes from DSP library
Definition at line 209 of file dsps_biquad_gen_f32.c.
{
    if (qFactor <= 0.0001) {
        qFactor = 0.0001;
    }
    float Fs = 1;
    float w0 = 2 * M_PI * f / Fs;
    float c = cosf(w0);
    float s = sinf(w0);
    float alpha = s / (2 * qFactor);
    float b0 = alpha;
    float b1 = 0;
    float b2 = -alpha;
    float a0 = 1 + alpha;
    float a1 = -2 * c;
    float a2 = 1 - alpha;
    coeffs[0] = b0 / a0;
    coeffs[1] = b1 / a0;
    coeffs[2] = b2 / a0;
    coeffs[3] = a1 / a0;
    coeffs[4] = a2 / a0;
    return ESP_OK;
}
References coeffs, ESP_OK, and M_PI.