ESP-IDF Firmware: graphics_support.h File Reference
graphics_support.h File Reference
#include "esp_dsp.h"
#include "ekf_imu13states.h"
#include <stdint.h>
Data Structures
struct image_3d_matrix_s
Data struct of 3d image matrix.
struct image_3d_matrix_kalman_s
Data struct of 3d image matrix with kalman filter object.
Macros
#define DEG_TO_RAD 0.01745329252f
#define RAD_TO_DEG 57.29577951f
#define MATRIX_SIZE 4
#define SSD1306_WIDTH 128
#define SSD1306_HEIGHT 64
#define SSD1606_X_CENTER (SSD1306_WIDTH / 2)
#define SSD1606_Y_CENTER (SSD1306_HEIGHT / 2)
Typedefs
typedef struct image_3d_matrix_s image_3d_matrix_t
Data struct of 3d image matrix.
typedef struct image_3d_matrix_kalman_s image_3d_matrix_kalman_t
Data struct of 3d image matrix with kalman filter object.
Functions
void init_perspective_matrix (dspm::Mat &P_m)
initialize perspective projection matrix
void update_scaling_matrix (dspm::Mat &T_m, bool keep_diagonal, float scale_x, float scale_y, float scale_z)
update scaling matrix
void update_translation_matrix (dspm::Mat &T_m, bool row, float move_x, float move_y, float move_z)
update translation matrix
void update_rotation_matrix (dspm::Mat &T_m, float rot_x, float rot_y, float rot_z)
update rotation matrix
void update_perspective_matrix (dspm::Mat &P_m, float fov)
update perspective matrix
void print_matrix (dspm::Mat matrix)
printf matrix to the terminal output
Macro Definition Documentation
DEG_TO_RAD
#define DEG_TO_RAD 0.01745329252f
Definition at line 20 of file external_examples/f9c2d4b3/azure_board_apps/graphics/3d_matrix/3d_matrix_src/graphics_support.h.
MATRIX_SIZE
#define MATRIX_SIZE 4
Definition at line 22 of file external_examples/f9c2d4b3/azure_board_apps/graphics/3d_matrix/3d_matrix_src/graphics_support.h.
RAD_TO_DEG
#define RAD_TO_DEG 57.29577951f
Definition at line 21 of file external_examples/f9c2d4b3/azure_board_apps/graphics/3d_matrix/3d_matrix_src/graphics_support.h.
SSD1306_HEIGHT
#define SSD1306_HEIGHT 64
Definition at line 24 of file external_examples/f9c2d4b3/azure_board_apps/graphics/3d_matrix/3d_matrix_src/graphics_support.h.
SSD1306_WIDTH
#define SSD1306_WIDTH 128
Definition at line 23 of file external_examples/f9c2d4b3/azure_board_apps/graphics/3d_matrix/3d_matrix_src/graphics_support.h.
SSD1606_X_CENTER
#define SSD1606_X_CENTER (SSD1306_WIDTH / 2)
Definition at line 25 of file external_examples/f9c2d4b3/azure_board_apps/graphics/3d_matrix/3d_matrix_src/graphics_support.h.
SSD1606_Y_CENTER
#define SSD1606_Y_CENTER (SSD1306_HEIGHT / 2)
Definition at line 26 of file external_examples/f9c2d4b3/azure_board_apps/graphics/3d_matrix/3d_matrix_src/graphics_support.h.
Typedef Documentation
image_3d_matrix_kalman_t
typedef struct image_3d_matrix_kalman_s image_3d_matrix_kalman_t
Data struct of 3d image matrix with kalman filter object.
This structure is used to hold a 3d coordinates of a monochromatic image centered to the origin of the cartesian space (0, 0, 0), that has ben processed by the image_to_3d_array.py. Kalman filter object is added to the matrix, for the purpose of RTOS task arguments.
image_3d_matrix_t
typedef struct image_3d_matrix_s image_3d_matrix_t
Data struct of 3d image matrix.
This structure is used to hold a 3d coordinates of a monochromatic image centered to the origin of the cartesian space (0, 0, 0), that has ben processed by the image_to_3d_array.py.
Function Documentation
init_perspective_matrix()
void init_perspective_matrix (dspm::Mat & P_m)
initialize perspective projection matrix
Function initializes Mat class object holding perspective projection matrix.
Parameters
P_m perspective projection matrix object from the Mat class
Definition at line 12 of file applications/azure_board_apps/graphics/3d_matrix/3d_matrix_src/graphics_support.cpp.
{
    const float fov = 90;                           // field of view in degrees
    const float near = 0.0001;
    const float far = 1;
    const float S = 1 / (tan((fov / 2) * DEG_TO_RAD));
    // Initialize matrix to zero
    for (int row = 0; row < P_m.rows; row++) {
        for (int col = 0; col < P_m.cols; col++) {
            P_m(row, col) = 0;
        }
    }
    P_m(0, 0) = S;
    P_m(1, 1) = S;
    P_m(2, 2) = -far / (far - near);
    P_m(3, 2) = (-far * near) / (far - near);
    P_m(2, 3) = -1;
    P_m(3, 3) = 1;
}
References dspm::Mat::cols, DEG_TO_RAD, and dspm::Mat::rows.
Referenced by app_main().
print_matrix()
void print_matrix (dspm::Mat matrix)
printf matrix to the terminal output
Print matrix for debug purposes
Parameters
matrix matrix to be printed
Definition at line 105 of file applications/azure_board_apps/graphics/3d_matrix/3d_matrix_src/graphics_support.cpp.
{
    for (int rows = 0; rows < matrix.rows; rows++) {
        for (int cols = 0; cols < matrix.cols; cols++) {
            std::cout << matrix(rows, cols) << ", \t";
        }
        std::cout << std::endl;
    }
    std::cout << std::endl << std::endl;
}
References dspm::Mat::cols, and dspm::Mat::rows.
update_perspective_matrix()
void update_perspective_matrix (dspm::Mat & P_m, float fov)
update perspective matrix
Function updates perspective matrix with a new value of field of view
Parameters
P_m perspective projection matrix object from the Mat class
fov field of view in degrees
Definition at line 35 of file applications/azure_board_apps/graphics/3d_matrix/3d_matrix_src/graphics_support.cpp.
{
    const float near = 0.0001;
    const float far = 1;
    const float S = 1 / (tan((fov / 2) * DEG_TO_RAD));
    // Initialize matrix to zero
    for (int row = 0; row < P_m.rows; row++) {
        for (int col = 0; col < P_m.cols; col++) {
            P_m(row, col) = 0;
        }
    }
    P_m(0, 0) = S;
    P_m(1, 1) = S;
    P_m(2, 2) = -far / (far - near);
    P_m(3, 2) = (-far * near) / (far - near);
    P_m(2, 3) = -1;
    P_m(3, 3) = 1;
    P_m(3, 0) = (float)SSD1606_X_CENTER;
    P_m(3, 1) = (float)SSD1606_Y_CENTER;
}
References dspm::Mat::cols, DEG_TO_RAD, dspm::Mat::rows, SSD1606_X_CENTER, and SSD1606_Y_CENTER.
Referenced by draw_3d_image(), draw_3d_image(), draw_3d_image(), draw_3d_image(), get_pressure_task(), get_pressure_task(), get_pressure_task(), get_pressure_task(), kalman_filter_task(), kalman_filter_task(), kalman_filter_task(), and kalman_filter_task().
update_rotation_matrix()
void update_rotation_matrix (dspm::Mat & T_m, float rot_x, float rot_y, float rot_z)
update rotation matrix
Function updates rotation part of the tranformation matrix
Parameters
T_m transformation matrix object from the Mat class
rot_x rotation angle for x direction of the vector
rot_y rotation angle for y direction of the vector
rot_z rotation angle for z direction of the vector
Definition at line 87 of file applications/azure_board_apps/graphics/3d_matrix/3d_matrix_src/graphics_support.cpp.
{
    dspm::Mat rotation_data(3, 1);                      // matrix(3x1) that holds x, y, z rotation data
    rotation_data(0, 0) = DEG_TO_RAD * rot_x;           // rotation data x
    rotation_data(1, 0) = DEG_TO_RAD * rot_y;           // rotation data y
    rotation_data(2, 0) = DEG_TO_RAD * rot_z;           // rotation data z
    // Create and populate rotation matrix R(3x3). Then inverse it
    dspm::Mat R = ekf::eul2rotm(rotation_data.data).t();
    // Enlarge rotation matrix from 3x3 to 4x4
    for (int row = 0; row < R.rows; row++) {            // Copy rotation matrix R(3x3) to transformation matrix T_m(4x4)
        for (int col = 0; col < R.cols; col++) {
            T_m(row, col) = R(row, col);
        }
    }
}
References dspm::Mat::cols, dspm::Mat::data, DEG_TO_RAD, ekf::eul2rotm(), dspm::Mat::rows, and dspm::Mat::t().
Referenced by draw_3d_image(), draw_3d_image(), draw_3d_image(), draw_3d_image(), draw_3d_image_task(), draw_3d_image_task(), draw_3d_image_task(), draw_3d_image_task(), draw_3d_image_task(), draw_3d_image_task(), draw_3d_image_task(), and draw_3d_image_task().
update_scaling_matrix()
void update_scaling_matrix (dspm::Mat & T_m, bool keep_diagonal, float scale_x, float scale_y, float scale_z)
update scaling matrix
Function updates scaling part of the transformation matrix.
Parameters
T_m transformation matrix object from the Mat class
keep_diagonal if true: diagonal row of the transformation matrix T_m will be mulitplied with the scaling values if false: diagonal row of the transformation matrix T_m will be substituted with new scaling values
scale_x scaling value for x coordinate of the vector
scale_y scaling value for y coordinate of the vector
scale_z scaling value for z coordinate of the vector
Definition at line 60 of file applications/azure_board_apps/graphics/3d_matrix/3d_matrix_src/graphics_support.cpp.
{
    if (keep_diagonal) {                 // Multiply the diagonal values of the transformation matrix with the scaling
        T_m(0, 0) *= scale_x;            // (in case a rotation is already applied)
        T_m(1, 1) *= scale_y;
        T_m(2, 2) *= scale_z;
    } else {
        T_m(0, 0) = scale_x;
        T_m(1, 1) = scale_y;
        T_m(2, 2) = scale_z;
    }
}
Referenced by dispaly_esp_text(), dispaly_esp_text(), dispaly_esp_text(), dispaly_esp_text(), draw_3d_image_task(), and draw_3d_image_task().
update_translation_matrix()
void update_translation_matrix (dspm::Mat & T_m, bool row, float move_x, float move_y, float move_z)
update translation matrix
Function updates translation part of the transformation matrix.
Parameters
T_m transformation matrix object from the Mat class
row if true: translation values will be placed to the 3rd row of the transformation matrix T_m if false: translation values will be placed to the 3rd col of the transformation matrix T_m
move_x translation value for x coordinate of the vector
move_y translation value for y coordinate of the vector
move_z translation value for z coordinate of the vector
Definition at line 73 of file applications/azure_board_apps/graphics/3d_matrix/3d_matrix_src/graphics_support.cpp.
{
    if (row) {                      // update values in 4-th row, if translation matrix is the second multiplier
        T_m(3, 0) = move_x;
        T_m(3, 1) = move_y;
        T_m(3, 2) = move_z;
    } else {                        // update values in 4-th collum, if translation matrix is the first multiplier
        T_m(0, 3) = move_x;
        T_m(1, 3) = move_y;
        T_m(2, 3) = move_z;
    }
}
Referenced by dispaly_esp_text(), dispaly_esp_text(), dispaly_esp_text(), dispaly_esp_text(), draw_3d_image_task(), draw_3d_image_task(), draw_3d_image_task(), draw_3d_image_task(), draw_3d_image_task(), draw_3d_image_task(), draw_3d_image_task(), and draw_3d_image_task().