ESP-IDF Firmware: led_strip_rmt_encoder.h File Reference
led_strip_rmt_encoder.h File Reference
#include <stdint.h>
#include "driver/rmt_encoder.h"
#include "led_strip_types.h"
Data Structures
struct led_strip_encoder_config_t
Type of led strip encoder configuration.
Functions
esp_err_t rmt_new_led_strip_encoder (const led_strip_encoder_config_t *config, rmt_encoder_handle_t *ret_encoder)
Create RMT encoder for encoding LED strip pixels into RMT symbols.
Function Documentation
rmt_new_led_strip_encoder()
esp_err_t rmt_new_led_strip_encoder (const led_strip_encoder_config_t * config, rmt_encoder_handle_t * ret_encoder)
Create RMT encoder for encoding LED strip pixels into RMT symbols.
Parameters
[in] config Encoder configuration
[out] ret_encoder Returned encoder handle
Returns
ESP_ERR_INVALID_ARG for any invalid arguments
ESP_ERR_NO_MEM out of memory when creating led strip encoder
ESP_OK if creating encoder successfully
Definition at line 74 of file led_strip_rmt_encoder.c.
{
    esp_err_t ret = ESP_OK;
    rmt_led_strip_encoder_t *led_encoder = NULL;
    ESP_GOTO_ON_FALSE(config && ret_encoder, ESP_ERR_INVALID_ARG, err, TAG, "invalid argument");
    ESP_GOTO_ON_FALSE(config->led_model < LED_MODEL_INVALID, ESP_ERR_INVALID_ARG, err, TAG, "invalid led model");
    led_encoder = calloc(1, sizeof(rmt_led_strip_encoder_t));
    ESP_GOTO_ON_FALSE(led_encoder, ESP_ERR_NO_MEM, err, TAG, "no mem for led strip encoder");
    led_encoder->base.encode = rmt_encode_led_strip;
    led_encoder->base.del = rmt_del_led_strip_encoder;
    led_encoder->base.reset = rmt_led_strip_encoder_reset;
    rmt_bytes_encoder_config_t bytes_encoder_config;
    if (config->led_model == LED_MODEL_SK6812) {
        bytes_encoder_config = (rmt_bytes_encoder_config_t) {
            .bit0 = {
                .level0 = 1,
                .duration0 = 0.3 * config->resolution / 1000000, // T0H=0.3us
                .level1 = 0,
                .duration1 = 0.9 * config->resolution / 1000000, // T0L=0.9us
            },
            .bit1 = {
                .level0 = 1,
                .duration0 = 0.6 * config->resolution / 1000000, // T1H=0.6us
                .level1 = 0,
                .duration1 = 0.6 * config->resolution / 1000000, // T1L=0.6us
            },
            .flags.msb_first = 1 // SK6812 transfer bit order: G7...G0R7...R0B7...B0(W7...W0)
        };
    } else if (config->led_model == LED_MODEL_WS2812) {
        // different led strip might have its own timing requirements, following parameter is for WS2812
        bytes_encoder_config = (rmt_bytes_encoder_config_t) {
            .bit0 = {
                .level0 = 1,
                .duration0 = 0.3 * config->resolution / 1000000, // T0H=0.3us
                .level1 = 0,
                .duration1 = 0.9 * config->resolution / 1000000, // T0L=0.9us
            },
            .bit1 = {
                .level0 = 1,
                .duration0 = 0.9 * config->resolution / 1000000, // T1H=0.9us
                .level1 = 0,
                .duration1 = 0.3 * config->resolution / 1000000, // T1L=0.3us
            },
            .flags.msb_first = 1 // WS2812 transfer bit order: G7...G0R7...R0B7...B0
        };
    } else {
        assert(false);
    }
    ESP_GOTO_ON_ERROR(rmt_new_bytes_encoder(&bytes_encoder_config, &led_encoder->bytes_encoder), err, TAG, "create bytes encoder failed");
    rmt_copy_encoder_config_t copy_encoder_config = {};
    ESP_GOTO_ON_ERROR(rmt_new_copy_encoder(&copy_encoder_config, &led_encoder->copy_encoder), err, TAG, "create copy encoder failed");
    uint32_t reset_ticks = config->resolution / 1000000 * 280 / 2; // reset code duration defaults to 280us to accomodate WS2812B-V5
    led_encoder->reset_code = (rmt_symbol_word_t) {
        .level0 = 0,
        .duration0 = reset_ticks,
        .level1 = 0,
        .duration1 = reset_ticks,
    };
    *ret_encoder = &led_encoder->base;
    return ESP_OK;
err:
    if (led_encoder) {
        if (led_encoder->bytes_encoder) {
            rmt_del_encoder(led_encoder->bytes_encoder);
        }
        if (led_encoder->copy_encoder) {
            rmt_del_encoder(led_encoder->copy_encoder);
        }
        free(led_encoder);
    }
    return ret;
}
References rmt_led_strip_encoder_t::base, rmt_led_strip_encoder_t::bytes_encoder, rmt_led_strip_encoder_t::copy_encoder, ESP_GOTO_ON_ERROR, ESP_OK, led_strip_encoder_config_t::led_model, LED_MODEL_INVALID, LED_MODEL_SK6812, LED_MODEL_WS2812, rmt_led_strip_encoder_t::reset_code, led_strip_encoder_config_t::resolution, rmt_del_led_strip_encoder(), rmt_encode_led_strip(), rmt_led_strip_encoder_reset(), and TAG.
Referenced by led_strip_new_rmt_device().