ESP-IDF Firmware: led_strip_rmt_dev_idf4.c File Reference
led_strip_rmt_dev_idf4.c File Reference
#include <stdlib.h>
#include <string.h>
#include <sys/cdefs.h>
#include "esp_log.h"
#include "esp_check.h"
#include "driver/rmt.h"
#include "led_strip.h"
#include "led_strip_interface.h"
Data Structures
struct led_strip_rmt_obj
Macros
#define WS2812_T0H_NS (300)
#define WS2812_T0L_NS (900)
#define WS2812_T1H_NS (900)
#define WS2812_T1L_NS (300)
#define SK6812_T0H_NS (300)
#define SK6812_T0L_NS (900)
#define SK6812_T1H_NS (600)
#define SK6812_T1L_NS (600)
#define LED_STRIP_RESET_MS (10)
#define LED_STRIP_RMT_DEFAULT_MEM_BLOCK_SYMBOLS 48
Functions
static void ws2812_rmt_adapter (const void *src, rmt_item32_t *dest, size_t src_size, size_t wanted_num, size_t *translated_size, size_t *item_num)
static esp_err_t led_strip_rmt_set_pixel (led_strip_t *strip, uint32_t index, uint32_t red, uint32_t green, uint32_t blue)
static esp_err_t led_strip_rmt_refresh (led_strip_t *strip)
static esp_err_t led_strip_rmt_clear (led_strip_t *strip)
static esp_err_t led_strip_rmt_del (led_strip_t *strip)
esp_err_t led_strip_new_rmt_device (const led_strip_config_t *led_config, const led_strip_rmt_config_t *dev_config, led_strip_handle_t *ret_strip)
Create LED strip based on RMT TX channel.
Variables
static const char * TAG = "led_strip_rmt"
static uint32_t led_t0h_ticks = 0
static uint32_t led_t1h_ticks = 0
static uint32_t led_t0l_ticks = 0
static uint32_t led_t1l_ticks = 0
Macro Definition Documentation
LED_STRIP_RESET_MS
#define LED_STRIP_RESET_MS (10)
Definition at line 27 of file led_strip_rmt_dev_idf4.c.
Referenced by led_strip_rmt_refresh().
LED_STRIP_RMT_DEFAULT_MEM_BLOCK_SYMBOLS
#define LED_STRIP_RMT_DEFAULT_MEM_BLOCK_SYMBOLS 48
Definition at line 33 of file led_strip_rmt_dev_idf4.c.
SK6812_T0H_NS
#define SK6812_T0H_NS (300)
Definition at line 22 of file led_strip_rmt_dev_idf4.c.
Referenced by led_strip_new_rmt_device().
SK6812_T0L_NS
#define SK6812_T0L_NS (900)
Definition at line 23 of file led_strip_rmt_dev_idf4.c.
Referenced by led_strip_new_rmt_device().
SK6812_T1H_NS
#define SK6812_T1H_NS (600)
Definition at line 24 of file led_strip_rmt_dev_idf4.c.
Referenced by led_strip_new_rmt_device().
SK6812_T1L_NS
#define SK6812_T1L_NS (600)
Definition at line 25 of file led_strip_rmt_dev_idf4.c.
Referenced by led_strip_new_rmt_device().
WS2812_T0H_NS
#define WS2812_T0H_NS (300)
Definition at line 17 of file led_strip_rmt_dev_idf4.c.
Referenced by led_strip_new_rmt_device().
WS2812_T0L_NS
#define WS2812_T0L_NS (900)
Definition at line 18 of file led_strip_rmt_dev_idf4.c.
Referenced by led_strip_new_rmt_device().
WS2812_T1H_NS
#define WS2812_T1H_NS (900)
Definition at line 19 of file led_strip_rmt_dev_idf4.c.
Referenced by led_strip_new_rmt_device().
WS2812_T1L_NS
#define WS2812_T1L_NS (300)
Definition at line 20 of file led_strip_rmt_dev_idf4.c.
Referenced by led_strip_new_rmt_device().
Function Documentation
led_strip_new_rmt_device()
esp_err_t led_strip_new_rmt_device (const led_strip_config_t * led_config, const led_strip_rmt_config_t * rmt_config, led_strip_handle_t * ret_strip)
Create LED strip based on RMT TX channel.
Parameters
led_config LED strip configuration
rmt_config RMT specific configuration
ret_strip Returned LED strip handle
Returns
ESP_OK: create LED strip handle successfully
ESP_ERR_INVALID_ARG: create LED strip handle failed because of invalid argument
ESP_ERR_NO_MEM: create LED strip handle failed because of out of memory
ESP_FAIL: create LED strip handle failed because some other error
Definition at line 121 of file led_strip_rmt_dev_idf4.c.
{
    led_strip_rmt_obj *rmt_strip = NULL;
    esp_err_t ret = ESP_OK;
    ESP_RETURN_ON_FALSE(led_config && dev_config && ret_strip, ESP_ERR_INVALID_ARG, TAG, "invalid argument");
    ESP_RETURN_ON_FALSE(led_config->led_pixel_format < LED_PIXEL_FORMAT_INVALID, ESP_ERR_INVALID_ARG, TAG, "invalid led_pixel_format");
    ESP_RETURN_ON_FALSE(dev_config->flags.with_dma == 0, ESP_ERR_NOT_SUPPORTED, TAG, "DMA is not supported");
    uint8_t bytes_per_pixel = 3;
    if (led_config->led_pixel_format == LED_PIXEL_FORMAT_GRBW) {
        bytes_per_pixel = 4;
    } else if (led_config->led_pixel_format == LED_PIXEL_FORMAT_GRB) {
        bytes_per_pixel = 3;
    } else {
        assert(false);
    }
    // allocate memory for led_strip object
    rmt_strip = calloc(1, sizeof(led_strip_rmt_obj) + led_config->max_leds * bytes_per_pixel);
    ESP_RETURN_ON_FALSE(rmt_strip, ESP_ERR_NO_MEM, TAG, "request memory for les_strip failed");
    // install RMT channel driver
    rmt_config_t config = RMT_DEFAULT_CONFIG_TX(led_config->strip_gpio_num, dev_config->rmt_channel);
    // set the minimal clock division because the LED strip needs a high clock resolution
    config.clk_div = 2;
    uint8_t mem_block_num = 2;
    // override the default value if the user specify the mem block size
    if (dev_config->mem_block_symbols) {
        mem_block_num = (dev_config->mem_block_symbols + LED_STRIP_RMT_DEFAULT_MEM_BLOCK_SYMBOLS / 2) / LED_STRIP_RMT_DEFAULT_MEM_BLOCK_SYMBOLS;
    }
    config.mem_block_num = mem_block_num;
    ESP_GOTO_ON_ERROR(rmt_config(&config), err, TAG, "RMT config failed");
    ESP_GOTO_ON_ERROR(rmt_driver_install(config.channel, 0, 0), err, TAG, "RMT install failed");
    uint32_t counter_clk_hz = 0;
    rmt_get_counter_clock((rmt_channel_t)dev_config->rmt_channel, &counter_clk_hz);
    // ns -> ticks
    float ratio = (float)counter_clk_hz / 1e9;
    if (led_config->led_model == LED_MODEL_WS2812) {
        led_t0h_ticks = (uint32_t)(ratio * WS2812_T0H_NS);
        led_t0l_ticks = (uint32_t)(ratio * WS2812_T0L_NS);
        led_t1h_ticks = (uint32_t)(ratio * WS2812_T1H_NS);
        led_t1l_ticks = (uint32_t)(ratio * WS2812_T1L_NS);
    } else if (led_config->led_model == LED_MODEL_SK6812) {
        led_t0h_ticks = (uint32_t)(ratio * SK6812_T0H_NS);
        led_t0l_ticks = (uint32_t)(ratio * SK6812_T0L_NS);
        led_t1h_ticks = (uint32_t)(ratio * SK6812_T1H_NS);
        led_t1l_ticks = (uint32_t)(ratio * SK6812_T1L_NS);
    } else {
        assert(false);
    }
    // adapter to translates the LES strip date frame into RMT symbols
    rmt_translator_init((rmt_channel_t)dev_config->rmt_channel, ws2812_rmt_adapter);
    rmt_strip->bytes_per_pixel = bytes_per_pixel;
    rmt_strip->rmt_channel = (rmt_channel_t)dev_config->rmt_channel;
    rmt_strip->strip_len = led_config->max_leds;
    rmt_strip->base.set_pixel = led_strip_rmt_set_pixel;
    rmt_strip->base.refresh = led_strip_rmt_refresh;
    rmt_strip->base.clear = led_strip_rmt_clear;
    rmt_strip->base.del = led_strip_rmt_del;
    *ret_strip = &rmt_strip->base;
    return ESP_OK;
err:
    if (rmt_strip) {
        free(rmt_strip);
    }
    return ret;
}
References led_strip_rmt_obj::base, led_strip_rmt_obj::bytes_per_pixel, led_strip_t::clear, led_strip_rmt_config_t::clk_src, led_strip_t::del, ESP_GOTO_ON_ERROR, ESP_OK, led_strip_config_t::flags, led_strip_rmt_config_t::flags, led_strip_config_t::invert_out, led_strip_config_t::led_model, LED_MODEL_SK6812, LED_MODEL_WS2812, led_strip_config_t::led_pixel_format, LED_PIXEL_FORMAT_GRB, LED_PIXEL_FORMAT_GRBW, LED_PIXEL_FORMAT_INVALID, led_strip_rmt_clear(), LED_STRIP_RMT_DEFAULT_MEM_BLOCK_SYMBOLS, LED_STRIP_RMT_DEFAULT_RESOLUTION, LED_STRIP_RMT_DEFAULT_TRANS_QUEUE_SIZE, led_strip_rmt_del(), led_strip_rmt_refresh(), led_strip_rmt_set_pixel(), led_strip_rmt_set_pixel_rgbw(), led_t0h_ticks, led_t0l_ticks, led_t1h_ticks, led_t1l_ticks, led_strip_config_t::max_leds, led_strip_rmt_config_t::mem_block_symbols, led_strip_t::refresh, led_strip_rmt_config_t::resolution_hz, led_strip_rmt_obj::rmt_chan, led_strip_rmt_obj::rmt_channel, rmt_new_led_strip_encoder(), led_strip_t::set_pixel, led_strip_t::set_pixel_rgbw, SK6812_T0H_NS, SK6812_T0L_NS, SK6812_T1H_NS, SK6812_T1L_NS, led_strip_rmt_obj::strip_encoder, led_strip_config_t::strip_gpio_num, led_strip_rmt_obj::strip_len, TAG, led_strip_rmt_config_t::with_dma, ws2812_rmt_adapter(), WS2812_T0H_NS, WS2812_T0L_NS, WS2812_T1H_NS, and WS2812_T1L_NS.
led_strip_rmt_clear()
esp_err_t led_strip_rmt_clear (led_strip_t * strip) static
Definition at line 105 of file led_strip_rmt_dev_idf4.c.
{
    led_strip_rmt_obj *rmt_strip = __containerof(strip, led_strip_rmt_obj, base);
    // Write zero to turn off all LEDs
    memset(rmt_strip->buffer, 0, rmt_strip->strip_len * rmt_strip->bytes_per_pixel);
    return led_strip_rmt_refresh(strip);
}
References led_strip_rmt_obj::buffer, led_strip_rmt_obj::bytes_per_pixel, led_strip_rmt_refresh(), and led_strip_rmt_obj::strip_len.
led_strip_rmt_del()
esp_err_t led_strip_rmt_del (led_strip_t * strip) static
Definition at line 113 of file led_strip_rmt_dev_idf4.c.
{
    led_strip_rmt_obj *rmt_strip = __containerof(strip, led_strip_rmt_obj, base);
    ESP_RETURN_ON_ERROR(rmt_driver_uninstall(rmt_strip->rmt_channel), TAG, "uninstall RMT driver failed");
    free(rmt_strip);
    return ESP_OK;
}
References ESP_OK, ESP_RETURN_ON_ERROR, led_strip_rmt_obj::rmt_channel, and TAG.
led_strip_rmt_refresh()
esp_err_t led_strip_rmt_refresh (led_strip_t * strip) static
Definition at line 96 of file led_strip_rmt_dev_idf4.c.
{
    led_strip_rmt_obj *rmt_strip = __containerof(strip, led_strip_rmt_obj, base);
    ESP_RETURN_ON_ERROR(rmt_write_sample(rmt_strip->rmt_channel, rmt_strip->buffer, rmt_strip->strip_len * rmt_strip->bytes_per_pixel, true), TAG,
                        "transmit RMT samples failed");
    vTaskDelay(pdMS_TO_TICKS(LED_STRIP_RESET_MS));
    return ESP_OK;
}
References led_strip_rmt_obj::buffer, led_strip_rmt_obj::bytes_per_pixel, ESP_OK, ESP_RETURN_ON_ERROR, LED_STRIP_RESET_MS, led_strip_rmt_obj::rmt_channel, led_strip_rmt_obj::strip_len, and TAG.
Referenced by led_strip_rmt_clear().
led_strip_rmt_set_pixel()
esp_err_t led_strip_rmt_set_pixel (led_strip_t * strip, uint32_t index, uint32_t red, uint32_t green, uint32_t blue) static
Definition at line 81 of file led_strip_rmt_dev_idf4.c.
{
    led_strip_rmt_obj *rmt_strip = __containerof(strip, led_strip_rmt_obj, base);
    ESP_RETURN_ON_FALSE(index < rmt_strip->strip_len, ESP_ERR_INVALID_ARG, TAG, "index out of the maximum number of leds");
    uint32_t start = index * rmt_strip->bytes_per_pixel;
    // In thr order of GRB
    rmt_strip->buffer[start + 0] = green & 0xFF;
    rmt_strip->buffer[start + 1] = red & 0xFF;
    rmt_strip->buffer[start + 2] = blue & 0xFF;
    if (rmt_strip->bytes_per_pixel > 3) {
        rmt_strip->buffer[start + 3] = 0;
    }
    return ESP_OK;
}
References led_strip_rmt_obj::buffer, led_strip_rmt_obj::bytes_per_pixel, ESP_OK, and TAG.
ws2812_rmt_adapter()
void ws2812_rmt_adapter (const void * src, rmt_item32_t * dest, size_t src_size, size_t wanted_num, size_t * translated_size, size_t * item_num) static
Definition at line 49 of file led_strip_rmt_dev_idf4.c.
{
    if (src == NULL || dest == NULL) {
        *translated_size = 0;
        *item_num = 0;
        return;
    }
    const rmt_item32_t bit0 = {{{ led_t0h_ticks, 1, led_t0l_ticks, 0 }}}; //Logical 0
    const rmt_item32_t bit1 = {{{ led_t1h_ticks, 1, led_t1l_ticks, 0 }}}; //Logical 1
    size_t size = 0;
    size_t num = 0;
    uint8_t *psrc = (uint8_t *)src;
    rmt_item32_t *pdest = dest;
    while (size < src_size && num < wanted_num) {
        for (int i = 0; i < 8; i++) {
            // MSB first
            if (*psrc & (1 << (7 - i))) {
                pdest->val =  bit1.val;
            } else {
                pdest->val =  bit0.val;
            }
            num++;
            pdest++;
        }
        size++;
        psrc++;
    }
    *translated_size = size;
    *item_num = num;
}
References led_t0h_ticks, led_t0l_ticks, led_t1h_ticks, and led_t1l_ticks.
Referenced by led_strip_new_rmt_device().
Variable Documentation
led_t0h_ticks
uint32_t led_t0h_ticks = 0 static
Definition at line 36 of file led_strip_rmt_dev_idf4.c.
Referenced by led_strip_new_rmt_device(), and ws2812_rmt_adapter().
led_t0l_ticks
uint32_t led_t0l_ticks = 0 static
Definition at line 38 of file led_strip_rmt_dev_idf4.c.
Referenced by led_strip_new_rmt_device(), and ws2812_rmt_adapter().
led_t1h_ticks
uint32_t led_t1h_ticks = 0 static
Definition at line 37 of file led_strip_rmt_dev_idf4.c.
Referenced by led_strip_new_rmt_device(), and ws2812_rmt_adapter().
led_t1l_ticks
uint32_t led_t1l_ticks = 0 static
Definition at line 39 of file led_strip_rmt_dev_idf4.c.
Referenced by led_strip_new_rmt_device(), and ws2812_rmt_adapter().
TAG
const char* TAG = "led_strip_rmt" static
Definition at line 15 of file led_strip_rmt_dev_idf4.c.