ESP-IDF Firmware: led_strip_rmt.h File Reference
led_strip_rmt.h File Reference
#include <stdint.h>
#include "esp_err.h"
#include "led_strip_types.h"
#include "esp_idf_version.h"
#include "driver/rmt_types.h"
Data Structures
struct led_strip_rmt_config_t
LED Strip RMT specific configuration.
Functions
esp_err_t led_strip_new_rmt_device (const led_strip_config_t *led_config, const led_strip_rmt_config_t *rmt_config, led_strip_handle_t *ret_strip)
Create LED strip based on RMT TX channel.
Function Documentation
led_strip_new_rmt_device()
esp_err_t led_strip_new_rmt_device (const led_strip_config_t * led_config, const led_strip_rmt_config_t * rmt_config, led_strip_handle_t * ret_strip)
Create LED strip based on RMT TX channel.
Parameters
led_config LED strip configuration
rmt_config RMT specific configuration
ret_strip Returned LED strip handle
Returns
ESP_OK: create LED strip handle successfully
ESP_ERR_INVALID_ARG: create LED strip handle failed because of invalid argument
ESP_ERR_NO_MEM: create LED strip handle failed because of out of memory
ESP_FAIL: create LED strip handle failed because some other error
Definition at line 97 of file led_strip_rmt_dev.c.
{
    led_strip_rmt_obj *rmt_strip = NULL;
    esp_err_t ret = ESP_OK;
    ESP_GOTO_ON_FALSE(led_config && rmt_config && ret_strip, ESP_ERR_INVALID_ARG, err, TAG, "invalid argument");
    ESP_GOTO_ON_FALSE(led_config->led_pixel_format < LED_PIXEL_FORMAT_INVALID, ESP_ERR_INVALID_ARG, err, TAG, "invalid led_pixel_format");
    uint8_t bytes_per_pixel = 3;
    if (led_config->led_pixel_format == LED_PIXEL_FORMAT_GRBW) {
        bytes_per_pixel = 4;
    } else if (led_config->led_pixel_format == LED_PIXEL_FORMAT_GRB) {
        bytes_per_pixel = 3;
    } else {
        assert(false);
    }
    rmt_strip = calloc(1, sizeof(led_strip_rmt_obj) + led_config->max_leds * bytes_per_pixel);
    ESP_GOTO_ON_FALSE(rmt_strip, ESP_ERR_NO_MEM, err, TAG, "no mem for rmt strip");
    uint32_t resolution = rmt_config->resolution_hz ? rmt_config->resolution_hz : LED_STRIP_RMT_DEFAULT_RESOLUTION;
    // for backward compatibility, if the user does not set the clk_src, use the default value
    rmt_clock_source_t clk_src = RMT_CLK_SRC_DEFAULT;
    if (rmt_config->clk_src) {
        clk_src = rmt_config->clk_src;
    }
    size_t mem_block_symbols = LED_STRIP_RMT_DEFAULT_MEM_BLOCK_SYMBOLS;
    // override the default value if the user sets it
    if (rmt_config->mem_block_symbols) {
        mem_block_symbols = rmt_config->mem_block_symbols;
    }
    rmt_tx_channel_config_t rmt_chan_config = {
        .clk_src = clk_src,
        .gpio_num = led_config->strip_gpio_num,
        .mem_block_symbols = mem_block_symbols,
        .resolution_hz = resolution,
        .trans_queue_depth = LED_STRIP_RMT_DEFAULT_TRANS_QUEUE_SIZE,
        .flags.with_dma = rmt_config->flags.with_dma,
        .flags.invert_out = led_config->flags.invert_out,
    };
    ESP_GOTO_ON_ERROR(rmt_new_tx_channel(&rmt_chan_config, &rmt_strip->rmt_chan), err, TAG, "create RMT TX channel failed");
    led_strip_encoder_config_t strip_encoder_conf = {
        .resolution = resolution,
        .led_model = led_config->led_model
    };
    ESP_GOTO_ON_ERROR(rmt_new_led_strip_encoder(&strip_encoder_conf, &rmt_strip->strip_encoder), err, TAG, "create LED strip encoder failed");
    rmt_strip->bytes_per_pixel = bytes_per_pixel;
    rmt_strip->strip_len = led_config->max_leds;
    rmt_strip->base.set_pixel = led_strip_rmt_set_pixel;
    rmt_strip->base.set_pixel_rgbw = led_strip_rmt_set_pixel_rgbw;
    rmt_strip->base.refresh = led_strip_rmt_refresh;
    rmt_strip->base.clear = led_strip_rmt_clear;
    rmt_strip->base.del = led_strip_rmt_del;
    *ret_strip = &rmt_strip->base;
    return ESP_OK;
err:
    if (rmt_strip) {
        if (rmt_strip->rmt_chan) {
            rmt_del_channel(rmt_strip->rmt_chan);
        }
        if (rmt_strip->strip_encoder) {
            rmt_del_encoder(rmt_strip->strip_encoder);
        }
        free(rmt_strip);
    }
    return ret;
}
References led_strip_rmt_obj::base, led_strip_rmt_obj::bytes_per_pixel, led_strip_t::clear, led_strip_rmt_config_t::clk_src, led_strip_t::del, ESP_GOTO_ON_ERROR, ESP_OK, led_strip_config_t::flags, led_strip_rmt_config_t::flags, led_strip_config_t::invert_out, led_strip_config_t::led_model, LED_MODEL_SK6812, LED_MODEL_WS2812, led_strip_config_t::led_pixel_format, LED_PIXEL_FORMAT_GRB, LED_PIXEL_FORMAT_GRBW, LED_PIXEL_FORMAT_INVALID, led_strip_rmt_clear(), LED_STRIP_RMT_DEFAULT_MEM_BLOCK_SYMBOLS, LED_STRIP_RMT_DEFAULT_RESOLUTION, LED_STRIP_RMT_DEFAULT_TRANS_QUEUE_SIZE, led_strip_rmt_del(), led_strip_rmt_refresh(), led_strip_rmt_set_pixel(), led_strip_rmt_set_pixel_rgbw(), led_t0h_ticks, led_t0l_ticks, led_t1h_ticks, led_t1l_ticks, led_strip_config_t::max_leds, led_strip_rmt_config_t::mem_block_symbols, led_strip_t::refresh, led_strip_rmt_config_t::resolution_hz, led_strip_rmt_obj::rmt_chan, led_strip_rmt_obj::rmt_channel, rmt_new_led_strip_encoder(), led_strip_t::set_pixel, led_strip_t::set_pixel_rgbw, SK6812_T0H_NS, SK6812_T0L_NS, SK6812_T1H_NS, SK6812_T1L_NS, led_strip_rmt_obj::strip_encoder, led_strip_config_t::strip_gpio_num, led_strip_rmt_obj::strip_len, TAG, led_strip_rmt_config_t::with_dma, ws2812_rmt_adapter(), WS2812_T0H_NS, WS2812_T0L_NS, WS2812_T1H_NS, and WS2812_T1L_NS.