ESP-IDF Firmware: image_3d_matrix_s Struct Reference
image_3d_matrix_s Struct Reference
Data struct of 3d image matrix.
#include <graphics_support.h>
Data Fields
const float(* matrix)[4]
uint32_t matrix_len
Detailed Description
Data struct of 3d image matrix.
This structure is used to hold a 3d coordinates of a monochromatic image centered to the origin of the cartesian space (0, 0, 0), that has ben processed by the image_to_3d_array.py.
Definition at line 34 of file applications/azure_board_apps/graphics/3d_matrix/3d_matrix_src/graphics_support.h.
Field Documentation
matrix
const float(* image_3d_matrix_s::matrix
matrix holding xyz coordinates for each point of the converted image.
Definition at line 35 of file applications/azure_board_apps/graphics/3d_matrix/3d_matrix_src/graphics_support.h.
Referenced by dispaly_esp_text(), dispaly_esp_text(), dispaly_esp_text(), and dispaly_esp_text().
matrix_len
uint32_t image_3d_matrix_s::matrix_len
image matrix length.
Definition at line 36 of file applications/azure_board_apps/graphics/3d_matrix/3d_matrix_src/graphics_support.h.
Referenced by dispaly_esp_text(), dispaly_esp_text(), dispaly_esp_text(), and dispaly_esp_text().
The documentation for this struct was generated from the following files:
applications/azure_board_apps/graphics/3d_matrix/3d_matrix_src/graphics_support.h
external_examples/b00f000e/applications/azure_board_apps/graphics/3d_matrix/3d_matrix_src/graphics_support.h
external_examples/f9c2d4b3/azure_board_apps/graphics/3d_matrix/3d_matrix_src/graphics_support.h