ESP-IDF Firmware: image_3d_matrix_kalman_s Struct Reference
image_3d_matrix_kalman_s Struct Reference
Data struct of 3d image matrix with kalman filter object.
#include <graphics_support.h>
Data Fields
const float(* matrix)[4]
uint32_t matrix_len
ekf_imu13states * ekf13
Detailed Description
Data struct of 3d image matrix with kalman filter object.
This structure is used to hold a 3d coordinates of a monochromatic image centered to the origin of the cartesian space (0, 0, 0), that has ben processed by the image_to_3d_array.py. Kalman filter object is added to the matrix, for the purpose of RTOS task arguments.
Definition at line 46 of file applications/azure_board_apps/graphics/3d_matrix/3d_matrix_src/graphics_support.h.
Field Documentation
ekf13
ekf_imu13states * image_3d_matrix_kalman_s::ekf13
kalman filter object.
Definition at line 49 of file applications/azure_board_apps/graphics/3d_matrix/3d_matrix_src/graphics_support.h.
Referenced by kalman_filter_task(), kalman_filter_task(), kalman_filter_task(), and kalman_filter_task().
matrix
const float(* image_3d_matrix_kalman_s::matrix
matrix holding xyz coordinates for each point of the converted image.
Definition at line 47 of file applications/azure_board_apps/graphics/3d_matrix/3d_matrix_src/graphics_support.h.
Referenced by kalman_filter_task(), kalman_filter_task(), kalman_filter_task(), and kalman_filter_task().
matrix_len
uint32_t image_3d_matrix_kalman_s::matrix_len
image matrix length.
Definition at line 48 of file applications/azure_board_apps/graphics/3d_matrix/3d_matrix_src/graphics_support.h.
Referenced by kalman_filter_task(), kalman_filter_task(), kalman_filter_task(), and kalman_filter_task().
The documentation for this struct was generated from the following files:
applications/azure_board_apps/graphics/3d_matrix/3d_matrix_src/graphics_support.h
external_examples/b00f000e/applications/azure_board_apps/graphics/3d_matrix/3d_matrix_src/graphics_support.h
external_examples/f9c2d4b3/azure_board_apps/graphics/3d_matrix/3d_matrix_src/graphics_support.h