ESP-IDF Firmware: test_fft2r.c File Reference
test_fft2r.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "dsp_common.h"
#include "dspm_mult.h"
#include "dsps_fft2r.h"
Macros
#define test_size 128
Functions
void xt_iss_profile_disable ()
void xt_iss_profile_enable ()
bool dsp_is_power_of_two (int x)
check power of two The function check if the argument is power of 2. The implementation use ANSI C and could be compiled and run on any platform
int dsp_power_of_two (int x)
Power of two The function return power of 2 for values 2^N. The implementation use ANSI C and could be compiled and run on any platform.
void test_fft2r ()
Variables
static float data [128 *2]
static float check_data [128 *2]
static float data_test [128 *2]
Macro Definition Documentation
test_size
#define test_size 128
Definition at line 32 of file test_fft2r.c.
Function Documentation
dsp_is_power_of_two()
bool dsp_is_power_of_two (int x)
check power of two The function check if the argument is power of 2. The implementation use ANSI C and could be compiled and run on any platform
Returns
true if x is power of two
false if no
Definition at line 16 of file test_fft2r.c.
{
    return (x != 0) && ((x & (x - 1)) == 0);
}
References x.
Referenced by dsps_bit_rev4r_direct_fc32_ansi(), dsps_bit_rev_fc32_ansi(), dsps_bit_rev_sc16_ansi(), dsps_cplx2reC_fc32_ansi(), dsps_cplx2reC_sc16(), dsps_cplx_gen_freq_get(), dsps_cplx_gen_init(), dsps_cplx_gen_phase_get(), dsps_fft2r_fc32_ansi_(), dsps_fft2r_sc16_ansi_(), dsps_gen_bitrev2r_table(), dsps_gen_bitrev4r_table(), dsps_gen_w_r2_fc32(), dsps_gen_w_r2_sc16(), dsps_sfdr_f32(), and dsps_snr_f32().
dsp_power_of_two()
int dsp_power_of_two (int x)
Power of two The function return power of 2 for values 2^N. The implementation use ANSI C and could be compiled and run on any platform.
Returns
power of two
Definition at line 21 of file test_fft2r.c.
{
    for (size_t i = 0; i < 16; i++) {
        x = x >> 1;
        if (0 == x) {
            return i;
        }
    }
    return 0;
}
References x.
Referenced by dsps_bit_rev4r_direct_fc32_ansi(), dsps_cplx2real_sc16_ansi(), dsps_fft2r_init_fc32(), dsps_fft4r_fc32_ansi_(), dsps_fft4r_init_fc32(), and dsps_gen_bitrev4r_table().
test_fft2r()
void test_fft2r ()
Definition at line 38 of file test_fft2r.c.
{
    int N = sizeof(data) / sizeof(float) / 2;
    int check_bin = 32;
    float check_ampl = 2000;
    for (int i = 0 ; i < N ; i++) {
        data[i * 2 + 0] = check_ampl * sinf(M_PI / N * check_bin * 2 * i) / (N / 2);
        data[i * 2 + 1] = 2;
    }
    for (int i = 0 ; i < N * 2 ; i++) {
        check_data[i] = data[i];
        data_test[i] = -1;
    }
    // Init FFT tables
    esp_err_t ret = dsps_fft2r_init_fc32(NULL, 4096);
    TEST_ESP_OK(ret);
    int N_check = N;
    // table = (uint16_t *)dsps_fft2r_rev_tables_fc32[6];
    // table_size = dsps_fft2r_rev_tables_fc32_size[6];
    xt_iss_profile_enable();
    dsps_fft2r_fc32(data, N_check);
//    dsps_bit_rev_lookup_fc32_ae32(data, N_check, dsps_fft2r_rev_tables_fc32[6]);
    dsps_fft2r_fc32_aes3_(check_data, N_check, dsps_fft_w_table_fc32);
//    dsps_bit_rev_lookup_fc32_ae32(data, N_check, dsps_fft2r_rev_tables_fc32[6]);
    xt_iss_profile_disable();
    for (int i = 0 ; i < N_check ; i++) {
        if (abs(check_data[i] - data[i]) == 0) {
            printf("Data[%i] =%8.4f, %8.4f, %f \n", i, data[i], check_data[i], check_data[i] - data[i]);
        } else {
            printf("ERROR: Data[%i] =%f, %f, %f \n", i, data[i], check_data[i], check_data[i] - data[i]);
        }
    }
    printf("Test Pass!\n");
}
References check_data, data, data_test, dsps_fft2r_fc32, dsps_fft2r_fc32_aes3_(), dsps_fft2r_init_fc32(), dsps_fft_w_table_fc32, M_PI, N, xt_iss_profile_disable(), and xt_iss_profile_enable().
Referenced by main().
xt_iss_profile_disable()
void xt_iss_profile_disable () extern
Referenced by test_fft2r(), and test_fir().
xt_iss_profile_enable()
void xt_iss_profile_enable () extern
Referenced by test_fft2r(), and test_fir().
Variable Documentation
check_data
float check_data[128 *2] static
Definition at line 35 of file test_fft2r.c.
Referenced by test_fft2r().
data
float data[128 *2] static
Definition at line 34 of file test_fft2r.c.
Referenced by __attribute__(), __led_strip_spi_bit(), bsp_enable_feature(), bsp_enable_feature(), build_frame(), dsps_bit_rev2r_fc32(), dsps_bit_rev4r_direct_fc32_ansi(), dsps_bit_rev4r_fc32(), dsps_bit_rev4r_fc32_ae32(), dsps_bit_rev4r_sc16_ansi(), dsps_bit_rev_fc32_ansi(), dsps_bit_rev_lookup_fc32_ae32(), dsps_bit_rev_lookup_fc32_aes3(), dsps_bit_rev_lookup_fc32_ansi(), dsps_bit_rev_sc16_ansi(), dsps_cplx2real256_fc32_ansi(), dsps_cplx2real_fc32_ae32_(), dsps_cplx2real_fc32_ansi_(), dsps_cplx2real_sc16_ansi(), dsps_cplx2reC_fc32_ansi(), dsps_cplx2reC_sc16(), dsps_dct_f32(), dsps_dct_f32_ref(), dsps_dct_inv_f32(), dsps_dct_inverce_f32_ref(), dsps_dctiv_f32(), dsps_dstiv_f32(), dsps_fft2r_fc32_ae32_(), dsps_fft2r_fc32_aes3_(), dsps_fft2r_fc32_ansi_(), dsps_fft2r_fc32_arp4_(), dsps_fft2r_sc16_ae32_(), dsps_fft2r_sc16_aes3_(), dsps_fft2r_sc16_ansi_(), dsps_fft2r_sc16_arp4_(), dsps_fft4r_fc32_ae32_(), dsps_fft4r_fc32_aes3_(), dsps_fft4r_fc32_ansi_(), dsps_fft4r_fc32_arp4_(), dsps_inverted_sqrtf_f32_ansi(), dsps_view(), dsps_view_s16(), dsps_view_spectrum(), frame_crc32(), read_bmi270_data(), read_bmm150_data(), spectrum2d_picture(), spectrum2d_picture(), test_fft2r(), tusb_read(), tusb_write(), write_bmi270_data(), write_bmi270_reg(), and write_bmm150_data().
data_test
float data_test[128 *2] static
Definition at line 36 of file test_fft2r.c.
Referenced by test_fft2r().