ESP-IDF Firmware: test_iir_biquad.c File Reference
test_iir_biquad.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "dsp_common.h"
#include "dsps_biquad.h"
Macros
#define N_SAMPLES 1024
Functions
void xt_iss_profile_disable ()
void xt_iss_profile_enable ()
esp_err_t dsps_biquad_f32_aes3 (const float *input, float *output, int len, float *coef, float *w)
void test_iir_biquad ()
Variables
int N = 1024
float d [1024]
float y [1024]
float y_ref [1024]
Macro Definition Documentation
N_SAMPLES
#define N_SAMPLES 1024
Definition at line 10 of file test_iir_biquad.c.
Function Documentation
dsps_biquad_f32_aes3()
esp_err_t dsps_biquad_f32_aes3 (const float * input, float * output, int len, float * coef, float * w)
Referenced by test_iir_biquad().
test_iir_biquad()
void test_iir_biquad ()
Definition at line 22 of file test_iir_biquad.c.
{
    float coeffs_lpf[5] = {0.073802,  0.147603,  0.073802,  -1.250516,  0.545723};
    float w_lpf[5] = {0, 0};
    float w_lpf_ref[5] = {0, 0};
    esp_err_t ret = ESP_OK;
    for (size_t i = 0; i < N; i++) {
        d[i] = 0;
    }
    d[0] = 1;
    xt_iss_profile_enable();
    ret = dsps_biquad_f32_ansi(d, y_ref, N, coeffs_lpf, w_lpf_ref);
    xt_iss_profile_disable();
    if (ret  != ESP_OK) {
        printf("dsps_biquad_f32 error = %i\n", ret);
        return;
    }
    xt_iss_profile_enable();
    ret = dsps_biquad_f32_aes3(d, y, N, coeffs_lpf, w_lpf);
    xt_iss_profile_disable();
    if (ret  != ESP_OK) {
        printf("dsps_biquad_f32 error = %i\n", ret);
        return;
    }
    for (size_t i = 0; i < N; i++) {
        if (((y[i] - y_ref[i]) > 0.0000001) || (y[i] - y_ref[i]) < -0.0000001) {
            printf("ERROR result[%i]: %f, expect = %f, diff=%f\n", i, y[i], y_ref[i], y[i] - y_ref[i]);
            return;
        }
    }
    printf("Test Correct!\n");
}
References d, dsps_biquad_f32_aes3(), dsps_biquad_f32_ansi(), ESP_OK, N, xt_iss_profile_disable(), xt_iss_profile_enable(), y, and y_ref.
Referenced by main().
xt_iss_profile_disable()
void xt_iss_profile_disable () extern
Referenced by test_iir_biquad().
xt_iss_profile_enable()
void xt_iss_profile_enable () extern
Referenced by test_iir_biquad().
Variable Documentation
d
float d[1024]
Definition at line 13 of file test_iir_biquad.c.
Referenced by test_iir_biquad().
N
int N = 1024
Definition at line 11 of file test_iir_biquad.c.
y
float y[1024]
Definition at line 15 of file test_iir_biquad.c.
y_ref
float y_ref[1024]
Definition at line 16 of file test_iir_biquad.c.
Referenced by test_iir_biquad().