ESP-IDF Firmware: tusb_console.h File Reference
tusb_console.h File Reference
#include "esp_err.h"
Functions
esp_err_t esp_tusb_init_console (int cdc_intf)
Redirect output to the USB serial.
esp_err_t esp_tusb_deinit_console (int cdc_intf)
Switch log to the default output.
Function Documentation
esp_tusb_deinit_console()
esp_err_t esp_tusb_deinit_console (int cdc_intf)
Switch log to the default output.
Parameters
cdc_intf - interface number of TinyUSB's CDC
Returns
esp_err_t
Definition at line 110 of file tusb_console.c.
{
    ESP_RETURN_ON_ERROR(restore_std_streams(&con.in, &con.out, &con.err), TAG, "Failed to restore STD streams");
    esp_vfs_tusb_cdc_unregister(NULL);
    return ESP_OK;
}
References con, ESP_OK, ESP_RETURN_ON_ERROR, esp_vfs_tusb_cdc_unregister(), restore_std_streams(), and TAG.
esp_tusb_init_console()
esp_err_t esp_tusb_init_console (int cdc_intf)
Redirect output to the USB serial.
Parameters
cdc_intf - interface number of TinyUSB's CDC
Returns
esp_err_t - ESP_OK, ESP_FAIL or an error code
Definition at line 102 of file tusb_console.c.
{
    /* Registering TUSB at VFS */
    ESP_RETURN_ON_ERROR(esp_vfs_tusb_cdc_register(cdc_intf, NULL), TAG, "");
    ESP_RETURN_ON_ERROR(redirect_std_streams_to(&con.in, &con.out, &con.err, VFS_TUSB_PATH_DEFAULT), TAG, "Failed to redirect STD streams");
    return ESP_OK;
}
References con, ESP_OK, ESP_RETURN_ON_ERROR, esp_vfs_tusb_cdc_register(), redirect_std_streams_to(), TAG, and VFS_TUSB_PATH_DEFAULT.