ESP-IDF Firmware: vfs_tinyusb.h File Reference
vfs_tinyusb.h File Reference
#include "esp_err.h"
Macros
#define VFS_TUSB_MAX_PATH 16
#define VFS_TUSB_PATH_DEFAULT "/dev/tusb_cdc"
Functions
esp_err_t esp_vfs_tusb_cdc_register (int cdc_intf, char const *path)
Register TinyUSB CDC at VFS with path.
esp_err_t esp_vfs_tusb_cdc_unregister (char const *path)
Unregister TinyUSB CDC from VFS.
Macro Definition Documentation
VFS_TUSB_MAX_PATH
#define VFS_TUSB_MAX_PATH 16
Definition at line 15 of file vfs_tinyusb.h.
Referenced by apply_path().
VFS_TUSB_PATH_DEFAULT
#define VFS_TUSB_PATH_DEFAULT "/dev/tusb_cdc"
Definition at line 16 of file vfs_tinyusb.h.
Referenced by apply_path(), esp_tusb_init_console(), and esp_vfs_tusb_cdc_unregister().
Function Documentation
esp_vfs_tusb_cdc_register()
esp_err_t esp_vfs_tusb_cdc_register (int cdc_intf, char const * path)
Register TinyUSB CDC at VFS with path.
Parameters
cdc_intf - interface number of TinyUSB's CDC
path - path where the CDC will be registered, /dev/tusb_cdc will be used if left NULL.
Returns
esp_err_t ESP_OK or ESP_FAIL
Definition at line 256 of file vfs_tinyusb.c.
{
    ESP_LOGD(TAG, "Registering TinyUSB CDC driver");
    int res;
    if (!tusb_cdc_acm_initialized(cdc_intf)) {
        ESP_LOGE(TAG, "TinyUSB CDC#%d is not initialized", cdc_intf);
        return ESP_ERR_INVALID_STATE;
    }
    res = vfstusb_init(cdc_intf, path);
    if (res != ESP_OK) {
        return res;
    }
    esp_vfs_t vfs = {
        .flags = ESP_VFS_FLAG_DEFAULT,
        .close = &tusb_close,
        .fcntl = &tusb_fcntl,
        .fstat = &tusb_fstat,
        .open = &tusb_open,
        .read = &tusb_read,
        .write = &tusb_write,
    };
    res = esp_vfs_register(s_vfstusb.vfs_path, &vfs, NULL);
    if (res != ESP_OK) {
        ESP_LOGE(TAG, "Can't register TinyUSB driver (err: %x)", res);
    } else {
        ESP_LOGD(TAG, "TinyUSB CDC registered (%s)", s_vfstusb.vfs_path);
    }
    return res;
}
References ESP_LOGD, ESP_OK, s_vfstusb, TAG, tusb_cdc_acm_initialized(), tusb_close(), tusb_fcntl(), tusb_fstat(), tusb_open(), tusb_read(), tusb_write(), and vfstusb_init().
Referenced by esp_tusb_init_console().
esp_vfs_tusb_cdc_unregister()
esp_err_t esp_vfs_tusb_cdc_unregister (char const * path)
Unregister TinyUSB CDC from VFS.
Parameters
path - path where the CDC will be unregistered if NULL will be used /dev/tusb_cdc
Returns
esp_err_t ESP_OK or ESP_FAIL
Definition at line 224 of file vfs_tinyusb.c.
{
    ESP_LOGD(TAG, "Unregistering TinyUSB driver");
    int res;
    if (path == NULL) { // NULL means using the default path for unregistering: VFS_TUSB_PATH_DEFAULT
        res = strcmp(s_vfstusb.vfs_path, VFS_TUSB_PATH_DEFAULT);
    } else {
        res = strcmp(s_vfstusb.vfs_path, path);
    }
    if (res) {
        res = ESP_ERR_INVALID_ARG;
        ESP_LOGE(TAG, "There is no TinyUSB driver registerred to the path '%s' (err: 0x%x)", s_vfstusb.vfs_path, res);
        return res;
    }
    res = esp_vfs_unregister(s_vfstusb.vfs_path);
    if (res != ESP_OK) {
        ESP_LOGE(TAG, "Can't unregister TinyUSB driver from '%s' (err: 0x%x)", s_vfstusb.vfs_path, res);
    } else {
        ESP_LOGD(TAG, "Unregistered TinyUSB driver");
        vfstusb_deinit();
    }
    return res;
}
References ESP_LOGD, ESP_OK, s_vfstusb, TAG, VFS_TUSB_PATH_DEFAULT, and vfstusb_deinit().
Referenced by esp_tusb_deinit_console().