ESP-IDF Firmware: wave_gen.h File Reference
wave_gen.h File Reference
#include "esp_err.h"
Data Structures
struct wave_gen_config_t
Configuration structure for Wave Generator.
Enumerations
enum wave_type_t { WAVE_TYPE_SINE = 0 , WAVE_TYPE_SQUARE , WAVE_TYPE_TRIANGLE , WAVE_TYPE_SAWTOOTH }
Waveform types for generation.
Functions
esp_err_t wave_gen_init (const wave_gen_config_t *config)
Initialize the Wave Generator component.
esp_err_t wave_gen_start (void)
Start the wave generation task.
esp_err_t wave_gen_stop (void)
Stop the wave generation task.
void wave_gen_set_freq (float freq_hz)
Set the frequency of the generated wave.
void wave_gen_set_type (wave_type_t type)
Set the waveform type.
void wave_gen_set_volume (float volume)
Set the output volume/amplitude.
esp_err_t wave_gen_sdm_start (void)
Start the SDM sine generator (uses CONFIG_SDM_* settings).
esp_err_t wave_gen_sdm_stop (void)
Stop the SDM sine generator.
Enumeration Type Documentation
wave_type_t
enum wave_type_t
Waveform types for generation.
Enumerator
WAVE_TYPE_SINE
WAVE_TYPE_SQUARE
WAVE_TYPE_TRIANGLE
WAVE_TYPE_SAWTOOTH
Definition at line 12 of file wave_gen.h.
             {
    WAVE_TYPE_SINE = 0,
    WAVE_TYPE_SQUARE,
    WAVE_TYPE_TRIANGLE,
    WAVE_TYPE_SAWTOOTH
} wave_type_t;
Function Documentation
wave_gen_init()
esp_err_t wave_gen_init (const wave_gen_config_t * config)
Initialize the Wave Generator component.
Parameters
config Pointer to configuration structure
Returns
esp_err_t ESP_OK on success
Definition at line 213 of file wave_gen.c.
{
    if (tx_conn_handle) {
        ESP_LOGW(TAG, "Already initialized");
        return ESP_OK;
    }
    ESP_LOGI(TAG, "Initializing I2S Wave Gen (32-bit) on BCK:%d WS:%d DO:%d MCK:%d",
             config->bck_io_num, config->ws_io_num, config->data_out_num, config->mck_io_num);
    i2s_chan_config_t chan_cfg = I2S_CHANNEL_DEFAULT_CONFIG(I2S_NUM_AUTO, I2S_ROLE_MASTER);
    ESP_RETURN_ON_ERROR(i2s_new_channel(&chan_cfg, &tx_conn_handle, NULL), TAG, "Failed to create I2S channel");
    i2s_std_config_t std_cfg = {
        .clk_cfg = I2S_STD_CLK_DEFAULT_CONFIG(config->sample_rate),
        .slot_cfg = I2S_STD_PCM_SLOT_DEFAULT_CONFIG(I2S_DATA_BIT_WIDTH_32BIT, I2S_SLOT_MODE_STEREO),
        .gpio_cfg = {
            .mclk = config->mck_io_num, // Can be I2S_GPIO_UNUSED (-1)
            .bclk = config->bck_io_num,
            .ws = config->ws_io_num,
            .dout = config->data_out_num,
            .din = I2S_GPIO_UNUSED,
            .invert_flags = {
                .mclk_inv = false,
                .bclk_inv = false,
                .ws_inv = false,
            },
        },
    };
    // Some PCM5102 modules benefit from MCLK being enabled if wired,
    // but often they generate it internally from BCK if MCLK is floating/grounded.
    // The driver will handle pin configuration.
    ESP_RETURN_ON_ERROR(i2s_channel_init_std_mode(tx_conn_handle, &std_cfg), TAG, "Failed to init I2S std mode");
    s_sample_rate = config->sample_rate;
    return ESP_OK;
}
References wave_gen_config_t::bck_io_num, wave_gen_config_t::data_out_num, ESP_OK, ESP_RETURN_ON_ERROR, wave_gen_config_t::mck_io_num, s_sample_rate, wave_gen_config_t::sample_rate, TAG, tx_conn_handle, and wave_gen_config_t::ws_io_num.
Referenced by app_main().
wave_gen_sdm_start()
esp_err_t wave_gen_sdm_start (void)
Start the SDM sine generator (uses CONFIG_SDM_* settings).
Returns
esp_err_t ESP_OK on success
Definition at line 303 of file wave_gen.c.
{
#if WAVE_GEN_HAS_SDM
    if (s_sdm_running) {
        return ESP_OK;
    }
    ESP_LOGI(TAG, "Starting SDM sine on GPIO %d at %d Hz", CONFIG_SDM_GPIO, CONFIG_SDM_FREQ_HZ);
    ESP_RETURN_ON_ERROR(sdm_init((uint32_t)CONFIG_SDM_FREQ_HZ), TAG, "SDM init failed");
    s_sdm_running = true;
    return ESP_OK;
#else
    return ESP_ERR_NOT_SUPPORTED;
#endif
}
References ESP_OK, ESP_RETURN_ON_ERROR, and TAG.
Referenced by app_main().
wave_gen_sdm_stop()
esp_err_t wave_gen_sdm_stop (void)
Stop the SDM sine generator.
Returns
esp_err_t ESP_OK on success
Definition at line 318 of file wave_gen.c.
{
#if WAVE_GEN_HAS_SDM
    if (!s_sdm_running) {
        return ESP_OK;
    }
    s_sdm_running = false;
    sdm_deinit();
    return ESP_OK;
#else
    return ESP_ERR_NOT_SUPPORTED;
#endif
}
References ESP_OK.
wave_gen_set_freq()
void wave_gen_set_freq (float freq_hz)
Set the frequency of the generated wave.
Parameters
freq_hz Frequency in Hertz
Definition at line 284 of file wave_gen.c.
{
    if (freq_hz < 1.0f) freq_hz = 1.0f;
    if (freq_hz > (float)s_sample_rate / 2.0f) freq_hz = (float)s_sample_rate / 2.0f;
    s_frequency = freq_hz;
}
References s_frequency, and s_sample_rate.
wave_gen_set_type()
void wave_gen_set_type (wave_type_t type)
Set the waveform type.
Parameters
type One of wave_type_t
Definition at line 291 of file wave_gen.c.
{
    s_type = type;
}
References s_type.
Referenced by app_main().
wave_gen_set_volume()
void wave_gen_set_volume (float volume)
Set the output volume/amplitude.
Parameters
volume 0.0 to 1.0 (clamped)
Definition at line 296 of file wave_gen.c.
{
    if (volume < 0.0f) volume = 0.0f;
    if (volume > 1.0f) volume = 1.0f;
    s_volume = volume;
}
References s_volume.
Referenced by app_main().
wave_gen_start()
esp_err_t wave_gen_start (void)
Start the wave generation task.
Returns
esp_err_t ESP_OK on success
Definition at line 253 of file wave_gen.c.
{
    if (!tx_conn_handle) return ESP_FAIL;
    if (s_running) return ESP_OK;
    ESP_RETURN_ON_ERROR(i2s_channel_enable(tx_conn_handle), TAG, "Failed to enable channel");
    s_running = true;
    xTaskCreate(wave_gen_task, "wave_gen_task", 4096, NULL, 5, &s_wave_task_handle);
    ESP_LOGI(TAG, "Wave Gen Started");
    return ESP_OK;
}
References ESP_OK, ESP_RETURN_ON_ERROR, s_running, s_wave_task_handle, TAG, tx_conn_handle, and wave_gen_task().
Referenced by app_main().
wave_gen_stop()
esp_err_t wave_gen_stop (void)
Stop the wave generation task.
Returns
esp_err_t ESP_OK on success
Definition at line 266 of file wave_gen.c.
{
    if (!s_running) return ESP_OK;
    s_running = false;
    // Wait for task or just let it spin down?
    // For simplicity, we assume task sees s_running false and exits.
    // Ideally we'd join or wait.
    // Allow task to exit loop
    vTaskDelay(pdMS_TO_TICKS(100));
    if (tx_conn_handle) {
        i2s_channel_disable(tx_conn_handle);
    }
    ESP_LOGI(TAG, "Wave Gen Stopped");
    return ESP_OK;
}
References ESP_OK, s_running, TAG, and tx_conn_handle.